/* This autogenerated file is part of jpcsp. */
/*
This file is part of jpcsp.

Jpcsp is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

Jpcsp is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with Jpcsp.  If not, see <http://www.gnu.org/licenses/>.
 */

package jpcsp.HLE.modules150;

import jpcsp.HLE.Modules;
import jpcsp.HLE.modules.HLEModule;
import jpcsp.HLE.modules.HLEModuleFunction;
import jpcsp.HLE.modules.HLEModuleManager;

import jpcsp.Memory;
import jpcsp.Processor;

import jpcsp.Allegrex.CpuState; // New-Style Processor

public class sceVshCommonUtil implements HLEModule {
	@Override
	public String getName() { return "sceVshCommonUtil"; }
	
	@Override
	public void installModule(HLEModuleManager mm, int version) {
		if (version >= 150) {
		
			mm.addFunction(sceVshCommonUtil_7A1C6D74Function, 0x7A1C6D74);
			mm.addFunction(sceVshCommonUtil_FC8E3CEFFunction, 0xFC8E3CEF);
			mm.addFunction(sceVshCommonUtil_BFC546B6Function, 0xBFC546B6);
			mm.addFunction(sceVshCommonUtil_7EEFA381Function, 0x7EEFA381);
			mm.addFunction(vshRegSysconfGetParentalLockLevelFunction, 0x5A3449D5);
			mm.addFunction(sceVshCommonUtil_0713D516Function, 0x0713D516);
			mm.addFunction(sceVshCommonUtil_12F5429AFunction, 0x12F5429A);
			mm.addFunction(sceVshCommonUtil_3FAF35ECFunction, 0x3FAF35EC);
			mm.addFunction(sceVshCommonUtil_0AF412FCFunction, 0x0AF412FC);
			mm.addFunction(sceVshCommonUtil_686AAA1AFunction, 0x686AAA1A);
			mm.addFunction(sceVshCommonUtil_249059B5Function, 0x249059B5);
			mm.addFunction(sceVshCommonUtil_7683BE4DFunction, 0x7683BE4D);
			mm.addFunction(sceVshCommonUtil_5A0B7762Function, 0x5A0B7762);
			mm.addFunction(sceVshCommonUtil_B296D591Function, 0xB296D591);
			mm.addFunction(vshRegSysconfInitRegistryFunction, 0xC403411C);
			mm.addFunction(sceVshCommonUtil_B48D135BFunction, 0xB48D135B);
			mm.addFunction(sceVshCommonUtil_63FFE887Function, 0x63FFE887);
			mm.addFunction(sceVshCommonUtil_28B6AD3BFunction, 0x28B6AD3B);
			mm.addFunction(sceVshCommonUtil_2ACAD845Function, 0x2ACAD845);
			mm.addFunction(sceVshCommonUtil_98E57F6DFunction, 0x98E57F6D);
			mm.addFunction(sceVshCommonUtil_3088B748Function, 0x3088B748);
			mm.addFunction(sceVshCommonUtil_EE5869D8Function, 0xEE5869D8);
			mm.addFunction(sceVshCommonUtil_81B52E61Function, 0x81B52E61);
			mm.addFunction(sceVshCommonUtil_9E7D761EFunction, 0x9E7D761E);
			mm.addFunction(sceVshCommonUtil_0F553311Function, 0x0F553311);
			mm.addFunction(sceSystemFileAddIndexWFunction, 0x15AF8184);
			mm.addFunction(sceSystemFileCalcSizeWFunction, 0x27627379);
			mm.addFunction(sceSystemFileFreeFunction, 0xEDED68FB);
			mm.addFunction(sceSystemFileGetIndexFunction, 0x2D564AF6);
			mm.addFunction(sceSystemFileGetIndexInfoFunction, 0x6B332472);
			mm.addFunction(sceSystemFileGetValueFunction, 0xF857F095);
			mm.addFunction(sceSystemFileGetValuePtrFunction, 0x9A2C3824);
			mm.addFunction(sceSystemFileInitFormatWFunction, 0x46931A6C);
			mm.addFunction(sceSystemFileLoadAllFunction, 0xB6E7804E);
			mm.addFunction(sceSystemFileLoadIndexFunction, 0xE55CADD9);
			mm.addFunction(sceVshCommonUtil_024CEB82Function, 0x024CEB82);
			mm.addFunction(vshRegSysconfGetAuthPasswordFunction, 0x3412B578);
			mm.addFunction(vshRegSysconfCloseRegistryFunction, 0x3E95607D);
			mm.addFunction(vshRegSysconfGetRegistryFunction, 0x53CF01CA);
			mm.addFunction(vshRegSysconfOpenRegistryFunction, 0x8727574A);
			mm.addFunction(vshRegSysconfGetDateTimeFormatFunction, 0x36BA6A54);
			mm.addFunction(vshRegSysconfGetDisplayLanguageFunction, 0x79FF29A4);
			mm.addFunction(vshRegSysconfGetSummerTimeModeFunction, 0x9845E69B);
			mm.addFunction(vshRegSysconfGetTimezoneAreaFunction, 0xBA7237F4);
			mm.addFunction(vshRegSysconfGetUserNameFunction, 0x29278272);
			mm.addFunction(vshRegSysconfSetAuthPasswordFunction, 0xCFB4A59E);
			mm.addFunction(vshRegSysconfSetDisplayLanguageFunction, 0x1815FB1F);
			mm.addFunction(vshRegSysconfSetRegistryFunction, 0x53120F49);
			mm.addFunction(vshRegSysconfSetTimezoneAreaFunction, 0xDEB009C6);
			mm.addFunction(vshRegSysconfSetTimezoneOffsetFunction, 0xD9E2759B);
			mm.addFunction(vshRegSysconfSetUserNameFunction, 0x75477C22);
			mm.addFunction(vshRegSysconfUpdateRegistryFunction, 0x58234CB0);
			mm.addFunction(sceVshCommonUtil_FA969B6AFunction, 0xFA969B6A);
			mm.addFunction(sceVshCommonUtil_D4D66154Function, 0xD4D66154);
			mm.addFunction(sceVshCommonUtil_9DF53F2FFunction, 0x9DF53F2F);
			mm.addFunction(sceVshCommonUtil_107EDCD9Function, 0x107EDCD9);
			
		}
	}
	
	@Override
	public void uninstallModule(HLEModuleManager mm, int version) {
		if (version >= 150) {
		
			mm.removeFunction(sceVshCommonUtil_7A1C6D74Function);
			mm.removeFunction(sceVshCommonUtil_FC8E3CEFFunction);
			mm.removeFunction(sceVshCommonUtil_BFC546B6Function);
			mm.removeFunction(sceVshCommonUtil_7EEFA381Function);
			mm.removeFunction(vshRegSysconfGetParentalLockLevelFunction);
			mm.removeFunction(sceVshCommonUtil_0713D516Function);
			mm.removeFunction(sceVshCommonUtil_12F5429AFunction);
			mm.removeFunction(sceVshCommonUtil_3FAF35ECFunction);
			mm.removeFunction(sceVshCommonUtil_0AF412FCFunction);
			mm.removeFunction(sceVshCommonUtil_686AAA1AFunction);
			mm.removeFunction(sceVshCommonUtil_249059B5Function);
			mm.removeFunction(sceVshCommonUtil_7683BE4DFunction);
			mm.removeFunction(sceVshCommonUtil_5A0B7762Function);
			mm.removeFunction(sceVshCommonUtil_B296D591Function);
			mm.removeFunction(vshRegSysconfInitRegistryFunction);
			mm.removeFunction(sceVshCommonUtil_B48D135BFunction);
			mm.removeFunction(sceVshCommonUtil_63FFE887Function);
			mm.removeFunction(sceVshCommonUtil_28B6AD3BFunction);
			mm.removeFunction(sceVshCommonUtil_2ACAD845Function);
			mm.removeFunction(sceVshCommonUtil_98E57F6DFunction);
			mm.removeFunction(sceVshCommonUtil_3088B748Function);
			mm.removeFunction(sceVshCommonUtil_EE5869D8Function);
			mm.removeFunction(sceVshCommonUtil_81B52E61Function);
			mm.removeFunction(sceVshCommonUtil_9E7D761EFunction);
			mm.removeFunction(sceVshCommonUtil_0F553311Function);
			mm.removeFunction(sceSystemFileAddIndexWFunction);
			mm.removeFunction(sceSystemFileCalcSizeWFunction);
			mm.removeFunction(sceSystemFileFreeFunction);
			mm.removeFunction(sceSystemFileGetIndexFunction);
			mm.removeFunction(sceSystemFileGetIndexInfoFunction);
			mm.removeFunction(sceSystemFileGetValueFunction);
			mm.removeFunction(sceSystemFileGetValuePtrFunction);
			mm.removeFunction(sceSystemFileInitFormatWFunction);
			mm.removeFunction(sceSystemFileLoadAllFunction);
			mm.removeFunction(sceSystemFileLoadIndexFunction);
			mm.removeFunction(sceVshCommonUtil_024CEB82Function);
			mm.removeFunction(vshRegSysconfGetAuthPasswordFunction);
			mm.removeFunction(vshRegSysconfCloseRegistryFunction);
			mm.removeFunction(vshRegSysconfGetRegistryFunction);
			mm.removeFunction(vshRegSysconfOpenRegistryFunction);
			mm.removeFunction(vshRegSysconfGetDateTimeFormatFunction);
			mm.removeFunction(vshRegSysconfGetDisplayLanguageFunction);
			mm.removeFunction(vshRegSysconfGetSummerTimeModeFunction);
			mm.removeFunction(vshRegSysconfGetTimezoneAreaFunction);
			mm.removeFunction(vshRegSysconfGetUserNameFunction);
			mm.removeFunction(vshRegSysconfSetAuthPasswordFunction);
			mm.removeFunction(vshRegSysconfSetDisplayLanguageFunction);
			mm.removeFunction(vshRegSysconfSetRegistryFunction);
			mm.removeFunction(vshRegSysconfSetTimezoneAreaFunction);
			mm.removeFunction(vshRegSysconfSetTimezoneOffsetFunction);
			mm.removeFunction(vshRegSysconfSetUserNameFunction);
			mm.removeFunction(vshRegSysconfUpdateRegistryFunction);
			mm.removeFunction(sceVshCommonUtil_FA969B6AFunction);
			mm.removeFunction(sceVshCommonUtil_D4D66154Function);
			mm.removeFunction(sceVshCommonUtil_9DF53F2FFunction);
			mm.removeFunction(sceVshCommonUtil_107EDCD9Function);
			
		}
	}
	
	
	public void sceVshCommonUtil_7A1C6D74(Processor processor) {
		CpuState cpu = processor.cpu;

		Modules.log.debug("Unimplemented NID function sceVshCommonUtil_7A1C6D74 [0x7A1C6D74]");

		cpu.gpr[2] = 0xDEADC0DE;
	}
    
	public void sceVshCommonUtil_FC8E3CEF(Processor processor) {
		CpuState cpu = processor.cpu;

		Modules.log.debug("Unimplemented NID function sceVshCommonUtil_FC8E3CEF [0xFC8E3CEF]");

		cpu.gpr[2] = 0xDEADC0DE;
	}
    
	public void sceVshCommonUtil_BFC546B6(Processor processor) {
		CpuState cpu = processor.cpu;

		Modules.log.debug("Unimplemented NID function sceVshCommonUtil_BFC546B6 [0xBFC546B6]");

		cpu.gpr[2] = 0xDEADC0DE;
	}
    
	public void sceVshCommonUtil_7EEFA381(Processor processor) {
		CpuState cpu = processor.cpu;

		Modules.log.debug("Unimplemented NID function sceVshCommonUtil_7EEFA381 [0x7EEFA381]");

		cpu.gpr[2] = 0xDEADC0DE;
	}
    
	public void vshRegSysconfGetParentalLockLevel(Processor processor) {
		CpuState cpu = processor.cpu;

		Modules.log.debug("Unimplemented NID function vshRegSysconfGetParentalLockLevel [0x5A3449D5]");

		cpu.gpr[2] = 0xDEADC0DE;
	}
    
	public void sceVshCommonUtil_0713D516(Processor processor) {
		CpuState cpu = processor.cpu;

		Modules.log.debug("Unimplemented NID function sceVshCommonUtil_0713D516 [0x0713D516]");

		cpu.gpr[2] = 0xDEADC0DE;
	}
    
	public void sceVshCommonUtil_12F5429A(Processor processor) {
		CpuState cpu = processor.cpu;

		Modules.log.debug("Unimplemented NID function sceVshCommonUtil_12F5429A [0x12F5429A]");

		cpu.gpr[2] = 0xDEADC0DE;
	}
    
	public void sceVshCommonUtil_3FAF35EC(Processor processor) {
		CpuState cpu = processor.cpu;

		Modules.log.debug("Unimplemented NID function sceVshCommonUtil_3FAF35EC [0x3FAF35EC]");

		cpu.gpr[2] = 0xDEADC0DE;
	}
    
	public void sceVshCommonUtil_0AF412FC(Processor processor) {
		CpuState cpu = processor.cpu;

		Modules.log.debug("Unimplemented NID function sceVshCommonUtil_0AF412FC [0x0AF412FC]");

		cpu.gpr[2] = 0xDEADC0DE;
	}
    
	public void sceVshCommonUtil_686AAA1A(Processor processor) {
		CpuState cpu = processor.cpu;

		Modules.log.debug("Unimplemented NID function sceVshCommonUtil_686AAA1A [0x686AAA1A]");

		cpu.gpr[2] = 0xDEADC0DE;
	}
    
	public void sceVshCommonUtil_249059B5(Processor processor) {
		CpuState cpu = processor.cpu;

		Modules.log.debug("Unimplemented NID function sceVshCommonUtil_249059B5 [0x249059B5]");

		cpu.gpr[2] = 0xDEADC0DE;
	}
    
	public void sceVshCommonUtil_7683BE4D(Processor processor) {
		CpuState cpu = processor.cpu;

		Modules.log.debug("Unimplemented NID function sceVshCommonUtil_7683BE4D [0x7683BE4D]");

		cpu.gpr[2] = 0xDEADC0DE;
	}
    
	public void sceVshCommonUtil_5A0B7762(Processor processor) {
		CpuState cpu = processor.cpu;

		Modules.log.debug("Unimplemented NID function sceVshCommonUtil_5A0B7762 [0x5A0B7762]");

		cpu.gpr[2] = 0xDEADC0DE;
	}
    
	public void sceVshCommonUtil_B296D591(Processor processor) {
		CpuState cpu = processor.cpu;

		Modules.log.debug("Unimplemented NID function sceVshCommonUtil_B296D591 [0xB296D591]");

		cpu.gpr[2] = 0xDEADC0DE;
	}
    
	public void vshRegSysconfInitRegistry(Processor processor) {
		CpuState cpu = processor.cpu;

		Modules.log.debug("Unimplemented NID function vshRegSysconfInitRegistry [0xC403411C]");

		cpu.gpr[2] = 0xDEADC0DE;
	}
    
	public void sceVshCommonUtil_B48D135B(Processor processor) {
		CpuState cpu = processor.cpu;

		Modules.log.debug("Unimplemented NID function sceVshCommonUtil_B48D135B [0xB48D135B]");

		cpu.gpr[2] = 0xDEADC0DE;
	}
    
	public void sceVshCommonUtil_63FFE887(Processor processor) {
		CpuState cpu = processor.cpu;

		Modules.log.debug("Unimplemented NID function sceVshCommonUtil_63FFE887 [0x63FFE887]");

		cpu.gpr[2] = 0xDEADC0DE;
	}
    
	public void sceVshCommonUtil_28B6AD3B(Processor processor) {
		CpuState cpu = processor.cpu;

		Modules.log.debug("Unimplemented NID function sceVshCommonUtil_28B6AD3B [0x28B6AD3B]");

		cpu.gpr[2] = 0xDEADC0DE;
	}
    
	public void sceVshCommonUtil_2ACAD845(Processor processor) {
		CpuState cpu = processor.cpu;

		Modules.log.debug("Unimplemented NID function sceVshCommonUtil_2ACAD845 [0x2ACAD845]");

		cpu.gpr[2] = 0xDEADC0DE;
	}
    
	public void sceVshCommonUtil_98E57F6D(Processor processor) {
		CpuState cpu = processor.cpu;

		Modules.log.debug("Unimplemented NID function sceVshCommonUtil_98E57F6D [0x98E57F6D]");

		cpu.gpr[2] = 0xDEADC0DE;
	}
    
	public void sceVshCommonUtil_3088B748(Processor processor) {
		CpuState cpu = processor.cpu;

		Modules.log.debug("Unimplemented NID function sceVshCommonUtil_3088B748 [0x3088B748]");

		cpu.gpr[2] = 0xDEADC0DE;
	}
    
	public void sceVshCommonUtil_EE5869D8(Processor processor) {
		CpuState cpu = processor.cpu;

		Modules.log.debug("Unimplemented NID function sceVshCommonUtil_EE5869D8 [0xEE5869D8]");

		cpu.gpr[2] = 0xDEADC0DE;
	}
    
	public void sceVshCommonUtil_81B52E61(Processor processor) {
		CpuState cpu = processor.cpu;

		Modules.log.debug("Unimplemented NID function sceVshCommonUtil_81B52E61 [0x81B52E61]");

		cpu.gpr[2] = 0xDEADC0DE;
	}
    
	public void sceVshCommonUtil_9E7D761E(Processor processor) {
		CpuState cpu = processor.cpu;

		Modules.log.debug("Unimplemented NID function sceVshCommonUtil_9E7D761E [0x9E7D761E]");

		cpu.gpr[2] = 0xDEADC0DE;
	}
    
	public void sceVshCommonUtil_0F553311(Processor processor) {
		CpuState cpu = processor.cpu;

		Modules.log.debug("Unimplemented NID function sceVshCommonUtil_0F553311 [0x0F553311]");

		cpu.gpr[2] = 0xDEADC0DE;
	}
    
	public void sceSystemFileAddIndexW(Processor processor) {
		CpuState cpu = processor.cpu;

		Modules.log.debug("Unimplemented NID function sceSystemFileAddIndexW [0x15AF8184]");

		cpu.gpr[2] = 0xDEADC0DE;
	}
    
	public void sceSystemFileCalcSizeW(Processor processor) {
		CpuState cpu = processor.cpu;

		Modules.log.debug("Unimplemented NID function sceSystemFileCalcSizeW [0x27627379]");

		cpu.gpr[2] = 0xDEADC0DE;
	}
    
	public void sceSystemFileFree(Processor processor) {
		CpuState cpu = processor.cpu;

		Modules.log.debug("Unimplemented NID function sceSystemFileFree [0xEDED68FB]");

		cpu.gpr[2] = 0xDEADC0DE;
	}
    
	public void sceSystemFileGetIndex(Processor processor) {
		CpuState cpu = processor.cpu;

		Modules.log.debug("Unimplemented NID function sceSystemFileGetIndex [0x2D564AF6]");

		cpu.gpr[2] = 0xDEADC0DE;
	}
    
	public void sceSystemFileGetIndexInfo(Processor processor) {
		CpuState cpu = processor.cpu;

		Modules.log.debug("Unimplemented NID function sceSystemFileGetIndexInfo [0x6B332472]");

		cpu.gpr[2] = 0xDEADC0DE;
	}
    
	public void sceSystemFileGetValue(Processor processor) {
		CpuState cpu = processor.cpu;

		Modules.log.debug("Unimplemented NID function sceSystemFileGetValue [0xF857F095]");

		cpu.gpr[2] = 0xDEADC0DE;
	}
    
	public void sceSystemFileGetValuePtr(Processor processor) {
		CpuState cpu = processor.cpu;

		Modules.log.debug("Unimplemented NID function sceSystemFileGetValuePtr [0x9A2C3824]");

		cpu.gpr[2] = 0xDEADC0DE;
	}
    
	public void sceSystemFileInitFormatW(Processor processor) {
		CpuState cpu = processor.cpu;

		Modules.log.debug("Unimplemented NID function sceSystemFileInitFormatW [0x46931A6C]");

		cpu.gpr[2] = 0xDEADC0DE;
	}
    
	public void sceSystemFileLoadAll(Processor processor) {
		CpuState cpu = processor.cpu;

		Modules.log.debug("Unimplemented NID function sceSystemFileLoadAll [0xB6E7804E]");

		cpu.gpr[2] = 0xDEADC0DE;
	}
    
	public void sceSystemFileLoadIndex(Processor processor) {
		CpuState cpu = processor.cpu;

		Modules.log.debug("Unimplemented NID function sceSystemFileLoadIndex [0xE55CADD9]");

		cpu.gpr[2] = 0xDEADC0DE;
	}
    
	public void sceVshCommonUtil_024CEB82(Processor processor) {
		CpuState cpu = processor.cpu;

		Modules.log.debug("Unimplemented NID function sceVshCommonUtil_024CEB82 [0x024CEB82]");

		cpu.gpr[2] = 0xDEADC0DE;
	}
    
	public void vshRegSysconfGetAuthPassword(Processor processor) {
		CpuState cpu = processor.cpu;

		Modules.log.debug("Unimplemented NID function vshRegSysconfGetAuthPassword [0x3412B578]");

		cpu.gpr[2] = 0xDEADC0DE;
	}
    
	public void vshRegSysconfCloseRegistry(Processor processor) {
		CpuState cpu = processor.cpu;

		Modules.log.debug("Unimplemented NID function vshRegSysconfCloseRegistry [0x3E95607D]");

		cpu.gpr[2] = 0xDEADC0DE;
	}
    
	public void vshRegSysconfGetRegistry(Processor processor) {
		CpuState cpu = processor.cpu;

		Modules.log.debug("Unimplemented NID function vshRegSysconfGetRegistry [0x53CF01CA]");

		cpu.gpr[2] = 0xDEADC0DE;
	}
    
	public void vshRegSysconfOpenRegistry(Processor processor) {
		CpuState cpu = processor.cpu;

		Modules.log.debug("Unimplemented NID function vshRegSysconfOpenRegistry [0x8727574A]");

		cpu.gpr[2] = 0xDEADC0DE;
	}
    
	public void vshRegSysconfGetDateTimeFormat(Processor processor) {
		CpuState cpu = processor.cpu;

		Modules.log.debug("Unimplemented NID function vshRegSysconfGetDateTimeFormat [0x36BA6A54]");

		cpu.gpr[2] = 0xDEADC0DE;
	}
    
	public void vshRegSysconfGetDisplayLanguage(Processor processor) {
		CpuState cpu = processor.cpu;

		Modules.log.debug("Unimplemented NID function vshRegSysconfGetDisplayLanguage [0x79FF29A4]");

		cpu.gpr[2] = 0xDEADC0DE;
	}
    
	public void vshRegSysconfGetSummerTimeMode(Processor processor) {
		CpuState cpu = processor.cpu;

		Modules.log.debug("Unimplemented NID function vshRegSysconfGetSummerTimeMode [0x9845E69B]");

		cpu.gpr[2] = 0xDEADC0DE;
	}
    
	public void vshRegSysconfGetTimezoneArea(Processor processor) {
		CpuState cpu = processor.cpu;

		Modules.log.debug("Unimplemented NID function vshRegSysconfGetTimezoneArea [0xBA7237F4]");

		cpu.gpr[2] = 0xDEADC0DE;
	}
    
	public void vshRegSysconfGetUserName(Processor processor) {
		CpuState cpu = processor.cpu;

		Modules.log.debug("Unimplemented NID function vshRegSysconfGetUserName [0x29278272]");

		cpu.gpr[2] = 0xDEADC0DE;
	}
    
	public void vshRegSysconfSetAuthPassword(Processor processor) {
		CpuState cpu = processor.cpu;

		Modules.log.debug("Unimplemented NID function vshRegSysconfSetAuthPassword [0xCFB4A59E]");

		cpu.gpr[2] = 0xDEADC0DE;
	}
    
	public void vshRegSysconfSetDisplayLanguage(Processor processor) {
		CpuState cpu = processor.cpu;

		Modules.log.debug("Unimplemented NID function vshRegSysconfSetDisplayLanguage [0x1815FB1F]");

		cpu.gpr[2] = 0xDEADC0DE;
	}
    
	public void vshRegSysconfSetRegistry(Processor processor) {
		CpuState cpu = processor.cpu;

		Modules.log.debug("Unimplemented NID function vshRegSysconfSetRegistry [0x53120F49]");

		cpu.gpr[2] = 0xDEADC0DE;
	}
    
	public void vshRegSysconfSetTimezoneArea(Processor processor) {
		CpuState cpu = processor.cpu;

		Modules.log.debug("Unimplemented NID function vshRegSysconfSetTimezoneArea [0xDEB009C6]");

		cpu.gpr[2] = 0xDEADC0DE;
	}
    
	public void vshRegSysconfSetTimezoneOffset(Processor processor) {
		CpuState cpu = processor.cpu;

		Modules.log.debug("Unimplemented NID function vshRegSysconfSetTimezoneOffset [0xD9E2759B]");

		cpu.gpr[2] = 0xDEADC0DE;
	}
    
	public void vshRegSysconfSetUserName(Processor processor) {
		CpuState cpu = processor.cpu;

		Modules.log.debug("Unimplemented NID function vshRegSysconfSetUserName [0x75477C22]");

		cpu.gpr[2] = 0xDEADC0DE;
	}
    
	public void vshRegSysconfUpdateRegistry(Processor processor) {
		CpuState cpu = processor.cpu;

		Modules.log.debug("Unimplemented NID function vshRegSysconfUpdateRegistry [0x58234CB0]");

		cpu.gpr[2] = 0xDEADC0DE;
	}
    
	public void sceVshCommonUtil_FA969B6A(Processor processor) {
		CpuState cpu = processor.cpu;

		Modules.log.debug("Unimplemented NID function sceVshCommonUtil_FA969B6A [0xFA969B6A]");

		cpu.gpr[2] = 0xDEADC0DE;
	}
    
	public void sceVshCommonUtil_D4D66154(Processor processor) {
		CpuState cpu = processor.cpu;

		Modules.log.debug("Unimplemented NID function sceVshCommonUtil_D4D66154 [0xD4D66154]");

		cpu.gpr[2] = 0xDEADC0DE;
	}
    
	public void sceVshCommonUtil_9DF53F2F(Processor processor) {
		CpuState cpu = processor.cpu;

		Modules.log.debug("Unimplemented NID function sceVshCommonUtil_9DF53F2F [0x9DF53F2F]");

		cpu.gpr[2] = 0xDEADC0DE;
	}
    
	public void sceVshCommonUtil_107EDCD9(Processor processor) {
		CpuState cpu = processor.cpu;

		Modules.log.debug("Unimplemented NID function sceVshCommonUtil_107EDCD9 [0x107EDCD9]");

		cpu.gpr[2] = 0xDEADC0DE;
	}
    
	public final HLEModuleFunction sceVshCommonUtil_7A1C6D74Function = new HLEModuleFunction("sceVshCommonUtil", "sceVshCommonUtil_7A1C6D74") {
		@Override
		public final void execute(Processor processor) {
			sceVshCommonUtil_7A1C6D74(processor);
		}
		@Override
		public final String compiledString() {
			return "jpcsp.HLE.Modules.sceVshCommonUtilModule.sceVshCommonUtil_7A1C6D74(processor);";
		}
	};
    
	public final HLEModuleFunction sceVshCommonUtil_FC8E3CEFFunction = new HLEModuleFunction("sceVshCommonUtil", "sceVshCommonUtil_FC8E3CEF") {
		@Override
		public final void execute(Processor processor) {
			sceVshCommonUtil_FC8E3CEF(processor);
		}
		@Override
		public final String compiledString() {
			return "jpcsp.HLE.Modules.sceVshCommonUtilModule.sceVshCommonUtil_FC8E3CEF(processor);";
		}
	};
    
	public final HLEModuleFunction sceVshCommonUtil_BFC546B6Function = new HLEModuleFunction("sceVshCommonUtil", "sceVshCommonUtil_BFC546B6") {
		@Override
		public final void execute(Processor processor) {
			sceVshCommonUtil_BFC546B6(processor);
		}
		@Override
		public final String compiledString() {
			return "jpcsp.HLE.Modules.sceVshCommonUtilModule.sceVshCommonUtil_BFC546B6(processor);";
		}
	};
    
	public final HLEModuleFunction sceVshCommonUtil_7EEFA381Function = new HLEModuleFunction("sceVshCommonUtil", "sceVshCommonUtil_7EEFA381") {
		@Override
		public final void execute(Processor processor) {
			sceVshCommonUtil_7EEFA381(processor);
		}
		@Override
		public final String compiledString() {
			return "jpcsp.HLE.Modules.sceVshCommonUtilModule.sceVshCommonUtil_7EEFA381(processor);";
		}
	};
    
	public final HLEModuleFunction vshRegSysconfGetParentalLockLevelFunction = new HLEModuleFunction("sceVshCommonUtil", "vshRegSysconfGetParentalLockLevel") {
		@Override
		public final void execute(Processor processor) {
			vshRegSysconfGetParentalLockLevel(processor);
		}
		@Override
		public final String compiledString() {
			return "jpcsp.HLE.Modules.sceVshCommonUtilModule.vshRegSysconfGetParentalLockLevel(processor);";
		}
	};
    
	public final HLEModuleFunction sceVshCommonUtil_0713D516Function = new HLEModuleFunction("sceVshCommonUtil", "sceVshCommonUtil_0713D516") {
		@Override
		public final void execute(Processor processor) {
			sceVshCommonUtil_0713D516(processor);
		}
		@Override
		public final String compiledString() {
			return "jpcsp.HLE.Modules.sceVshCommonUtilModule.sceVshCommonUtil_0713D516(processor);";
		}
	};
    
	public final HLEModuleFunction sceVshCommonUtil_12F5429AFunction = new HLEModuleFunction("sceVshCommonUtil", "sceVshCommonUtil_12F5429A") {
		@Override
		public final void execute(Processor processor) {
			sceVshCommonUtil_12F5429A(processor);
		}
		@Override
		public final String compiledString() {
			return "jpcsp.HLE.Modules.sceVshCommonUtilModule.sceVshCommonUtil_12F5429A(processor);";
		}
	};
    
	public final HLEModuleFunction sceVshCommonUtil_3FAF35ECFunction = new HLEModuleFunction("sceVshCommonUtil", "sceVshCommonUtil_3FAF35EC") {
		@Override
		public final void execute(Processor processor) {
			sceVshCommonUtil_3FAF35EC(processor);
		}
		@Override
		public final String compiledString() {
			return "jpcsp.HLE.Modules.sceVshCommonUtilModule.sceVshCommonUtil_3FAF35EC(processor);";
		}
	};
    
	public final HLEModuleFunction sceVshCommonUtil_0AF412FCFunction = new HLEModuleFunction("sceVshCommonUtil", "sceVshCommonUtil_0AF412FC") {
		@Override
		public final void execute(Processor processor) {
			sceVshCommonUtil_0AF412FC(processor);
		}
		@Override
		public final String compiledString() {
			return "jpcsp.HLE.Modules.sceVshCommonUtilModule.sceVshCommonUtil_0AF412FC(processor);";
		}
	};
    
	public final HLEModuleFunction sceVshCommonUtil_686AAA1AFunction = new HLEModuleFunction("sceVshCommonUtil", "sceVshCommonUtil_686AAA1A") {
		@Override
		public final void execute(Processor processor) {
			sceVshCommonUtil_686AAA1A(processor);
		}
		@Override
		public final String compiledString() {
			return "jpcsp.HLE.Modules.sceVshCommonUtilModule.sceVshCommonUtil_686AAA1A(processor);";
		}
	};
    
	public final HLEModuleFunction sceVshCommonUtil_249059B5Function = new HLEModuleFunction("sceVshCommonUtil", "sceVshCommonUtil_249059B5") {
		@Override
		public final void execute(Processor processor) {
			sceVshCommonUtil_249059B5(processor);
		}
		@Override
		public final String compiledString() {
			return "jpcsp.HLE.Modules.sceVshCommonUtilModule.sceVshCommonUtil_249059B5(processor);";
		}
	};
    
	public final HLEModuleFunction sceVshCommonUtil_7683BE4DFunction = new HLEModuleFunction("sceVshCommonUtil", "sceVshCommonUtil_7683BE4D") {
		@Override
		public final void execute(Processor processor) {
			sceVshCommonUtil_7683BE4D(processor);
		}
		@Override
		public final String compiledString() {
			return "jpcsp.HLE.Modules.sceVshCommonUtilModule.sceVshCommonUtil_7683BE4D(processor);";
		}
	};
    
	public final HLEModuleFunction sceVshCommonUtil_5A0B7762Function = new HLEModuleFunction("sceVshCommonUtil", "sceVshCommonUtil_5A0B7762") {
		@Override
		public final void execute(Processor processor) {
			sceVshCommonUtil_5A0B7762(processor);
		}
		@Override
		public final String compiledString() {
			return "jpcsp.HLE.Modules.sceVshCommonUtilModule.sceVshCommonUtil_5A0B7762(processor);";
		}
	};
    
	public final HLEModuleFunction sceVshCommonUtil_B296D591Function = new HLEModuleFunction("sceVshCommonUtil", "sceVshCommonUtil_B296D591") {
		@Override
		public final void execute(Processor processor) {
			sceVshCommonUtil_B296D591(processor);
		}
		@Override
		public final String compiledString() {
			return "jpcsp.HLE.Modules.sceVshCommonUtilModule.sceVshCommonUtil_B296D591(processor);";
		}
	};
    
	public final HLEModuleFunction vshRegSysconfInitRegistryFunction = new HLEModuleFunction("sceVshCommonUtil", "vshRegSysconfInitRegistry") {
		@Override
		public final void execute(Processor processor) {
			vshRegSysconfInitRegistry(processor);
		}
		@Override
		public final String compiledString() {
			return "jpcsp.HLE.Modules.sceVshCommonUtilModule.vshRegSysconfInitRegistry(processor);";
		}
	};
    
	public final HLEModuleFunction sceVshCommonUtil_B48D135BFunction = new HLEModuleFunction("sceVshCommonUtil", "sceVshCommonUtil_B48D135B") {
		@Override
		public final void execute(Processor processor) {
			sceVshCommonUtil_B48D135B(processor);
		}
		@Override
		public final String compiledString() {
			return "jpcsp.HLE.Modules.sceVshCommonUtilModule.sceVshCommonUtil_B48D135B(processor);";
		}
	};
    
	public final HLEModuleFunction sceVshCommonUtil_63FFE887Function = new HLEModuleFunction("sceVshCommonUtil", "sceVshCommonUtil_63FFE887") {
		@Override
		public final void execute(Processor processor) {
			sceVshCommonUtil_63FFE887(processor);
		}
		@Override
		public final String compiledString() {
			return "jpcsp.HLE.Modules.sceVshCommonUtilModule.sceVshCommonUtil_63FFE887(processor);";
		}
	};
    
	public final HLEModuleFunction sceVshCommonUtil_28B6AD3BFunction = new HLEModuleFunction("sceVshCommonUtil", "sceVshCommonUtil_28B6AD3B") {
		@Override
		public final void execute(Processor processor) {
			sceVshCommonUtil_28B6AD3B(processor);
		}
		@Override
		public final String compiledString() {
			return "jpcsp.HLE.Modules.sceVshCommonUtilModule.sceVshCommonUtil_28B6AD3B(processor);";
		}
	};
    
	public final HLEModuleFunction sceVshCommonUtil_2ACAD845Function = new HLEModuleFunction("sceVshCommonUtil", "sceVshCommonUtil_2ACAD845") {
		@Override
		public final void execute(Processor processor) {
			sceVshCommonUtil_2ACAD845(processor);
		}
		@Override
		public final String compiledString() {
			return "jpcsp.HLE.Modules.sceVshCommonUtilModule.sceVshCommonUtil_2ACAD845(processor);";
		}
	};
    
	public final HLEModuleFunction sceVshCommonUtil_98E57F6DFunction = new HLEModuleFunction("sceVshCommonUtil", "sceVshCommonUtil_98E57F6D") {
		@Override
		public final void execute(Processor processor) {
			sceVshCommonUtil_98E57F6D(processor);
		}
		@Override
		public final String compiledString() {
			return "jpcsp.HLE.Modules.sceVshCommonUtilModule.sceVshCommonUtil_98E57F6D(processor);";
		}
	};
    
	public final HLEModuleFunction sceVshCommonUtil_3088B748Function = new HLEModuleFunction("sceVshCommonUtil", "sceVshCommonUtil_3088B748") {
		@Override
		public final void execute(Processor processor) {
			sceVshCommonUtil_3088B748(processor);
		}
		@Override
		public final String compiledString() {
			return "jpcsp.HLE.Modules.sceVshCommonUtilModule.sceVshCommonUtil_3088B748(processor);";
		}
	};
    
	public final HLEModuleFunction sceVshCommonUtil_EE5869D8Function = new HLEModuleFunction("sceVshCommonUtil", "sceVshCommonUtil_EE5869D8") {
		@Override
		public final void execute(Processor processor) {
			sceVshCommonUtil_EE5869D8(processor);
		}
		@Override
		public final String compiledString() {
			return "jpcsp.HLE.Modules.sceVshCommonUtilModule.sceVshCommonUtil_EE5869D8(processor);";
		}
	};
    
	public final HLEModuleFunction sceVshCommonUtil_81B52E61Function = new HLEModuleFunction("sceVshCommonUtil", "sceVshCommonUtil_81B52E61") {
		@Override
		public final void execute(Processor processor) {
			sceVshCommonUtil_81B52E61(processor);
		}
		@Override
		public final String compiledString() {
			return "jpcsp.HLE.Modules.sceVshCommonUtilModule.sceVshCommonUtil_81B52E61(processor);";
		}
	};
    
	public final HLEModuleFunction sceVshCommonUtil_9E7D761EFunction = new HLEModuleFunction("sceVshCommonUtil", "sceVshCommonUtil_9E7D761E") {
		@Override
		public final void execute(Processor processor) {
			sceVshCommonUtil_9E7D761E(processor);
		}
		@Override
		public final String compiledString() {
			return "jpcsp.HLE.Modules.sceVshCommonUtilModule.sceVshCommonUtil_9E7D761E(processor);";
		}
	};
    
	public final HLEModuleFunction sceVshCommonUtil_0F553311Function = new HLEModuleFunction("sceVshCommonUtil", "sceVshCommonUtil_0F553311") {
		@Override
		public final void execute(Processor processor) {
			sceVshCommonUtil_0F553311(processor);
		}
		@Override
		public final String compiledString() {
			return "jpcsp.HLE.Modules.sceVshCommonUtilModule.sceVshCommonUtil_0F553311(processor);";
		}
	};
    
	public final HLEModuleFunction sceSystemFileAddIndexWFunction = new HLEModuleFunction("sceVshCommonUtil", "sceSystemFileAddIndexW") {
		@Override
		public final void execute(Processor processor) {
			sceSystemFileAddIndexW(processor);
		}
		@Override
		public final String compiledString() {
			return "jpcsp.HLE.Modules.sceVshCommonUtilModule.sceSystemFileAddIndexW(processor);";
		}
	};
    
	public final HLEModuleFunction sceSystemFileCalcSizeWFunction = new HLEModuleFunction("sceVshCommonUtil", "sceSystemFileCalcSizeW") {
		@Override
		public final void execute(Processor processor) {
			sceSystemFileCalcSizeW(processor);
		}
		@Override
		public final String compiledString() {
			return "jpcsp.HLE.Modules.sceVshCommonUtilModule.sceSystemFileCalcSizeW(processor);";
		}
	};
    
	public final HLEModuleFunction sceSystemFileFreeFunction = new HLEModuleFunction("sceVshCommonUtil", "sceSystemFileFree") {
		@Override
		public final void execute(Processor processor) {
			sceSystemFileFree(processor);
		}
		@Override
		public final String compiledString() {
			return "jpcsp.HLE.Modules.sceVshCommonUtilModule.sceSystemFileFree(processor);";
		}
	};
    
	public final HLEModuleFunction sceSystemFileGetIndexFunction = new HLEModuleFunction("sceVshCommonUtil", "sceSystemFileGetIndex") {
		@Override
		public final void execute(Processor processor) {
			sceSystemFileGetIndex(processor);
		}
		@Override
		public final String compiledString() {
			return "jpcsp.HLE.Modules.sceVshCommonUtilModule.sceSystemFileGetIndex(processor);";
		}
	};
    
	public final HLEModuleFunction sceSystemFileGetIndexInfoFunction = new HLEModuleFunction("sceVshCommonUtil", "sceSystemFileGetIndexInfo") {
		@Override
		public final void execute(Processor processor) {
			sceSystemFileGetIndexInfo(processor);
		}
		@Override
		public final String compiledString() {
			return "jpcsp.HLE.Modules.sceVshCommonUtilModule.sceSystemFileGetIndexInfo(processor);";
		}
	};
    
	public final HLEModuleFunction sceSystemFileGetValueFunction = new HLEModuleFunction("sceVshCommonUtil", "sceSystemFileGetValue") {
		@Override
		public final void execute(Processor processor) {
			sceSystemFileGetValue(processor);
		}
		@Override
		public final String compiledString() {
			return "jpcsp.HLE.Modules.sceVshCommonUtilModule.sceSystemFileGetValue(processor);";
		}
	};
    
	public final HLEModuleFunction sceSystemFileGetValuePtrFunction = new HLEModuleFunction("sceVshCommonUtil", "sceSystemFileGetValuePtr") {
		@Override
		public final void execute(Processor processor) {
			sceSystemFileGetValuePtr(processor);
		}
		@Override
		public final String compiledString() {
			return "jpcsp.HLE.Modules.sceVshCommonUtilModule.sceSystemFileGetValuePtr(processor);";
		}
	};
    
	public final HLEModuleFunction sceSystemFileInitFormatWFunction = new HLEModuleFunction("sceVshCommonUtil", "sceSystemFileInitFormatW") {
		@Override
		public final void execute(Processor processor) {
			sceSystemFileInitFormatW(processor);
		}
		@Override
		public final String compiledString() {
			return "jpcsp.HLE.Modules.sceVshCommonUtilModule.sceSystemFileInitFormatW(processor);";
		}
	};
    
	public final HLEModuleFunction sceSystemFileLoadAllFunction = new HLEModuleFunction("sceVshCommonUtil", "sceSystemFileLoadAll") {
		@Override
		public final void execute(Processor processor) {
			sceSystemFileLoadAll(processor);
		}
		@Override
		public final String compiledString() {
			return "jpcsp.HLE.Modules.sceVshCommonUtilModule.sceSystemFileLoadAll(processor);";
		}
	};
    
	public final HLEModuleFunction sceSystemFileLoadIndexFunction = new HLEModuleFunction("sceVshCommonUtil", "sceSystemFileLoadIndex") {
		@Override
		public final void execute(Processor processor) {
			sceSystemFileLoadIndex(processor);
		}
		@Override
		public final String compiledString() {
			return "jpcsp.HLE.Modules.sceVshCommonUtilModule.sceSystemFileLoadIndex(processor);";
		}
	};
    
	public final HLEModuleFunction sceVshCommonUtil_024CEB82Function = new HLEModuleFunction("sceVshCommonUtil", "sceVshCommonUtil_024CEB82") {
		@Override
		public final void execute(Processor processor) {
			sceVshCommonUtil_024CEB82(processor);
		}
		@Override
		public final String compiledString() {
			return "jpcsp.HLE.Modules.sceVshCommonUtilModule.sceVshCommonUtil_024CEB82(processor);";
		}
	};
    
	public final HLEModuleFunction vshRegSysconfGetAuthPasswordFunction = new HLEModuleFunction("sceVshCommonUtil", "vshRegSysconfGetAuthPassword") {
		@Override
		public final void execute(Processor processor) {
			vshRegSysconfGetAuthPassword(processor);
		}
		@Override
		public final String compiledString() {
			return "jpcsp.HLE.Modules.sceVshCommonUtilModule.vshRegSysconfGetAuthPassword(processor);";
		}
	};
    
	public final HLEModuleFunction vshRegSysconfCloseRegistryFunction = new HLEModuleFunction("sceVshCommonUtil", "vshRegSysconfCloseRegistry") {
		@Override
		public final void execute(Processor processor) {
			vshRegSysconfCloseRegistry(processor);
		}
		@Override
		public final String compiledString() {
			return "jpcsp.HLE.Modules.sceVshCommonUtilModule.vshRegSysconfCloseRegistry(processor);";
		}
	};
    
	public final HLEModuleFunction vshRegSysconfGetRegistryFunction = new HLEModuleFunction("sceVshCommonUtil", "vshRegSysconfGetRegistry") {
		@Override
		public final void execute(Processor processor) {
			vshRegSysconfGetRegistry(processor);
		}
		@Override
		public final String compiledString() {
			return "jpcsp.HLE.Modules.sceVshCommonUtilModule.vshRegSysconfGetRegistry(processor);";
		}
	};
    
	public final HLEModuleFunction vshRegSysconfOpenRegistryFunction = new HLEModuleFunction("sceVshCommonUtil", "vshRegSysconfOpenRegistry") {
		@Override
		public final void execute(Processor processor) {
			vshRegSysconfOpenRegistry(processor);
		}
		@Override
		public final String compiledString() {
			return "jpcsp.HLE.Modules.sceVshCommonUtilModule.vshRegSysconfOpenRegistry(processor);";
		}
	};
    
	public final HLEModuleFunction vshRegSysconfGetDateTimeFormatFunction = new HLEModuleFunction("sceVshCommonUtil", "vshRegSysconfGetDateTimeFormat") {
		@Override
		public final void execute(Processor processor) {
			vshRegSysconfGetDateTimeFormat(processor);
		}
		@Override
		public final String compiledString() {
			return "jpcsp.HLE.Modules.sceVshCommonUtilModule.vshRegSysconfGetDateTimeFormat(processor);";
		}
	};
    
	public final HLEModuleFunction vshRegSysconfGetDisplayLanguageFunction = new HLEModuleFunction("sceVshCommonUtil", "vshRegSysconfGetDisplayLanguage") {
		@Override
		public final void execute(Processor processor) {
			vshRegSysconfGetDisplayLanguage(processor);
		}
		@Override
		public final String compiledString() {
			return "jpcsp.HLE.Modules.sceVshCommonUtilModule.vshRegSysconfGetDisplayLanguage(processor);";
		}
	};
    
	public final HLEModuleFunction vshRegSysconfGetSummerTimeModeFunction = new HLEModuleFunction("sceVshCommonUtil", "vshRegSysconfGetSummerTimeMode") {
		@Override
		public final void execute(Processor processor) {
			vshRegSysconfGetSummerTimeMode(processor);
		}
		@Override
		public final String compiledString() {
			return "jpcsp.HLE.Modules.sceVshCommonUtilModule.vshRegSysconfGetSummerTimeMode(processor);";
		}
	};
    
	public final HLEModuleFunction vshRegSysconfGetTimezoneAreaFunction = new HLEModuleFunction("sceVshCommonUtil", "vshRegSysconfGetTimezoneArea") {
		@Override
		public final void execute(Processor processor) {
			vshRegSysconfGetTimezoneArea(processor);
		}
		@Override
		public final String compiledString() {
			return "jpcsp.HLE.Modules.sceVshCommonUtilModule.vshRegSysconfGetTimezoneArea(processor);";
		}
	};
    
	public final HLEModuleFunction vshRegSysconfGetUserNameFunction = new HLEModuleFunction("sceVshCommonUtil", "vshRegSysconfGetUserName") {
		@Override
		public final void execute(Processor processor) {
			vshRegSysconfGetUserName(processor);
		}
		@Override
		public final String compiledString() {
			return "jpcsp.HLE.Modules.sceVshCommonUtilModule.vshRegSysconfGetUserName(processor);";
		}
	};
    
	public final HLEModuleFunction vshRegSysconfSetAuthPasswordFunction = new HLEModuleFunction("sceVshCommonUtil", "vshRegSysconfSetAuthPassword") {
		@Override
		public final void execute(Processor processor) {
			vshRegSysconfSetAuthPassword(processor);
		}
		@Override
		public final String compiledString() {
			return "jpcsp.HLE.Modules.sceVshCommonUtilModule.vshRegSysconfSetAuthPassword(processor);";
		}
	};
    
	public final HLEModuleFunction vshRegSysconfSetDisplayLanguageFunction = new HLEModuleFunction("sceVshCommonUtil", "vshRegSysconfSetDisplayLanguage") {
		@Override
		public final void execute(Processor processor) {
			vshRegSysconfSetDisplayLanguage(processor);
		}
		@Override
		public final String compiledString() {
			return "jpcsp.HLE.Modules.sceVshCommonUtilModule.vshRegSysconfSetDisplayLanguage(processor);";
		}
	};
    
	public final HLEModuleFunction vshRegSysconfSetRegistryFunction = new HLEModuleFunction("sceVshCommonUtil", "vshRegSysconfSetRegistry") {
		@Override
		public final void execute(Processor processor) {
			vshRegSysconfSetRegistry(processor);
		}
		@Override
		public final String compiledString() {
			return "jpcsp.HLE.Modules.sceVshCommonUtilModule.vshRegSysconfSetRegistry(processor);";
		}
	};
    
	public final HLEModuleFunction vshRegSysconfSetTimezoneAreaFunction = new HLEModuleFunction("sceVshCommonUtil", "vshRegSysconfSetTimezoneArea") {
		@Override
		public final void execute(Processor processor) {
			vshRegSysconfSetTimezoneArea(processor);
		}
		@Override
		public final String compiledString() {
			return "jpcsp.HLE.Modules.sceVshCommonUtilModule.vshRegSysconfSetTimezoneArea(processor);";
		}
	};
    
	public final HLEModuleFunction vshRegSysconfSetTimezoneOffsetFunction = new HLEModuleFunction("sceVshCommonUtil", "vshRegSysconfSetTimezoneOffset") {
		@Override
		public final void execute(Processor processor) {
			vshRegSysconfSetTimezoneOffset(processor);
		}
		@Override
		public final String compiledString() {
			return "jpcsp.HLE.Modules.sceVshCommonUtilModule.vshRegSysconfSetTimezoneOffset(processor);";
		}
	};
    
	public final HLEModuleFunction vshRegSysconfSetUserNameFunction = new HLEModuleFunction("sceVshCommonUtil", "vshRegSysconfSetUserName") {
		@Override
		public final void execute(Processor processor) {
			vshRegSysconfSetUserName(processor);
		}
		@Override
		public final String compiledString() {
			return "jpcsp.HLE.Modules.sceVshCommonUtilModule.vshRegSysconfSetUserName(processor);";
		}
	};
    
	public final HLEModuleFunction vshRegSysconfUpdateRegistryFunction = new HLEModuleFunction("sceVshCommonUtil", "vshRegSysconfUpdateRegistry") {
		@Override
		public final void execute(Processor processor) {
			vshRegSysconfUpdateRegistry(processor);
		}
		@Override
		public final String compiledString() {
			return "jpcsp.HLE.Modules.sceVshCommonUtilModule.vshRegSysconfUpdateRegistry(processor);";
		}
	};
    
	public final HLEModuleFunction sceVshCommonUtil_FA969B6AFunction = new HLEModuleFunction("sceVshCommonUtil", "sceVshCommonUtil_FA969B6A") {
		@Override
		public final void execute(Processor processor) {
			sceVshCommonUtil_FA969B6A(processor);
		}
		@Override
		public final String compiledString() {
			return "jpcsp.HLE.Modules.sceVshCommonUtilModule.sceVshCommonUtil_FA969B6A(processor);";
		}
	};
    
	public final HLEModuleFunction sceVshCommonUtil_D4D66154Function = new HLEModuleFunction("sceVshCommonUtil", "sceVshCommonUtil_D4D66154") {
		@Override
		public final void execute(Processor processor) {
			sceVshCommonUtil_D4D66154(processor);
		}
		@Override
		public final String compiledString() {
			return "jpcsp.HLE.Modules.sceVshCommonUtilModule.sceVshCommonUtil_D4D66154(processor);";
		}
	};
    
	public final HLEModuleFunction sceVshCommonUtil_9DF53F2FFunction = new HLEModuleFunction("sceVshCommonUtil", "sceVshCommonUtil_9DF53F2F") {
		@Override
		public final void execute(Processor processor) {
			sceVshCommonUtil_9DF53F2F(processor);
		}
		@Override
		public final String compiledString() {
			return "jpcsp.HLE.Modules.sceVshCommonUtilModule.sceVshCommonUtil_9DF53F2F(processor);";
		}
	};
    
	public final HLEModuleFunction sceVshCommonUtil_107EDCD9Function = new HLEModuleFunction("sceVshCommonUtil", "sceVshCommonUtil_107EDCD9") {
		@Override
		public final void execute(Processor processor) {
			sceVshCommonUtil_107EDCD9(processor);
		}
		@Override
		public final String compiledString() {
			return "jpcsp.HLE.Modules.sceVshCommonUtilModule.sceVshCommonUtil_107EDCD9(processor);";
		}
	};
    
};
