/* This autogenerated file is part of jpcsp. */
package jpcsp.HLE.modules;

import jpcsp.HLE.pspSysMem;
import jpcsp.Memory;
import jpcsp.Processor;

public class sceDmacplus_driver implements HLEModule {

    @Override
    public final String getName() {
        return "sceDmacplus_driver";
    }

    @Override
    public void installModule(HLEModuleManager mm, int version) {

        mm.add(sceDmacplusInit, 0xDF32F547);

        mm.add(sceDmacplusEnd, 0xE6219C61);

        mm.add(sceDmacplusQuerySuspend, 0xC748491D);

        mm.add(sceDmacplusSuspend, 0x853C5EC6);

        mm.add(sceDmacplusResume, 0xD49A5922);

        mm.add(sceDmacplusEnableIntr, 0xA7B05225);

        mm.add(sceDmacplusDisableIntr, 0xBF939272);

        mm.add(sceDmacplusQueryIntr, 0x6AA3D654);

        mm.add(sceDmacplusAcquireIntr, 0x0DA570C1);

        mm.add(sceDmacplusLcdcInit, 0xFE3F3228);

        mm.add(sceDmacplusLcdcEnd, 0xCDB039A7);

        mm.add(sceDmacplusLcdcQuerySuspend, 0xC3236D69);

        mm.add(sceDmacplusLcdcSuspend, 0xC8336549);

        mm.add(sceDmacplusLcdcResume, 0x42BEB349);

        mm.add(sceDmacplusLcdcSetBaseAddr, 0x29B50A82);

        mm.add(sceDmacplusLcdcGetBaseAddr, 0x58C380BB);

        mm.add(sceDmacplusLcdcSetFormat, 0x8AE579CD);

        mm.add(sceDmacplusLcdcGetFormat, 0x241601AE);

        mm.add(sceDmacplusLcdcEnable, 0xF8C7C180);

        mm.add(sceDmacplusLcdcDisable, 0x576522BC);

        mm.add(sceDmacplusAvcInit, 0xBEC10779);

        mm.add(sceDmacplusAvcEnd, 0x7AAE5443);

        mm.add(sceDmacplusAvcQuerySuspend, 0x1E7483D0);

        mm.add(sceDmacplusAvcSuspend, 0x168836CF);

        mm.add(sceDmacplusAvcResume, 0x5E32C8AF);

        mm.add(sceDmacplus_driver_B2EFA681, 0xB2EFA681);

        mm.add(sceDmacplus_driver_1D73DDA8, 0x1D73DDA8);

        mm.add(sceDmacplus_driver_74323807, 0x74323807);

        mm.add(sceDmacplusAvcSync, 0x3A98EE05);

        mm.add(sceDmacplusSc2MeInit, 0xFD8B15BC);

        mm.add(sceDmacplusSc2MeEnd, 0xF7DEC189);

        mm.add(sceDmacplusSc2MeQuerySuspend, 0xD0464B29);

        mm.add(sceDmacplusSc2MeSuspend, 0xFEE3392C);

        mm.add(sceDmacplusSc2MeResume, 0xC5B75E09);

        mm.add(sceDmacplusSc2MeNormal16, 0x4B980588);

        mm.add(sceDmacplusSc2MeLLI, 0x3438DA0B);

        mm.add(sceDmacplusSc2MeSync, 0x58DE4914);

        mm.add(sceDmacplusMe2ScInit, 0x1F5A80D0);

        mm.add(sceDmacplusMe2ScEnd, 0xD1E1567E);

        mm.add(sceDmacplusMe2ScQuerySuspend, 0x9393B40D);

        mm.add(sceDmacplusMe2ScSuspend, 0x6D4F8BD7);

        mm.add(sceDmacplusMe2ScResume, 0x78A55D62);

        mm.add(sceDmacplusMe2ScNormal16, 0xBE693828);

        mm.add(sceDmacplusMe2ScLLI, 0x2D5940FF);

        mm.add(sceDmacplusMe2ScSync, 0xAB49D2CB);

        mm.add(sceDmacplusSc128Init, 0xB6592A56);

        mm.add(sceDmacplusSc128End, 0x4F1B8D26);

        mm.add(sceDmacplusSc128QuerySuspend, 0x410ED0DD);

        mm.add(sceDmacplusSc128Suspend, 0x3DB353DB);

        mm.add(sceDmacplusSc128Resume, 0x97DCBBBF);

        mm.add(sceDmacplusSc128Memcpy, 0xC7D33466);

        mm.add(sceDmacplusSc128TryMemcpy, 0x28558DBF);

        mm.add(sceDmacplusSc128LLI, 0xFD183BCF);

    }

    @Override
    public void uninstallModule(HLEModuleManager mm, int version) {

        mm.remove(sceDmacplusInit);

        mm.remove(sceDmacplusEnd);

        mm.remove(sceDmacplusQuerySuspend);

        mm.remove(sceDmacplusSuspend);

        mm.remove(sceDmacplusResume);

        mm.remove(sceDmacplusEnableIntr);

        mm.remove(sceDmacplusDisableIntr);

        mm.remove(sceDmacplusQueryIntr);

        mm.remove(sceDmacplusAcquireIntr);

        mm.remove(sceDmacplusLcdcInit);

        mm.remove(sceDmacplusLcdcEnd);

        mm.remove(sceDmacplusLcdcQuerySuspend);

        mm.remove(sceDmacplusLcdcSuspend);

        mm.remove(sceDmacplusLcdcResume);

        mm.remove(sceDmacplusLcdcSetBaseAddr);

        mm.remove(sceDmacplusLcdcGetBaseAddr);

        mm.remove(sceDmacplusLcdcSetFormat);

        mm.remove(sceDmacplusLcdcGetFormat);

        mm.remove(sceDmacplusLcdcEnable);

        mm.remove(sceDmacplusLcdcDisable);

        mm.remove(sceDmacplusAvcInit);

        mm.remove(sceDmacplusAvcEnd);

        mm.remove(sceDmacplusAvcQuerySuspend);

        mm.remove(sceDmacplusAvcSuspend);

        mm.remove(sceDmacplusAvcResume);

        mm.remove(sceDmacplus_driver_B2EFA681);

        mm.remove(sceDmacplus_driver_1D73DDA8);

        mm.remove(sceDmacplus_driver_74323807);

        mm.remove(sceDmacplusAvcSync);

        mm.remove(sceDmacplusSc2MeInit);

        mm.remove(sceDmacplusSc2MeEnd);

        mm.remove(sceDmacplusSc2MeQuerySuspend);

        mm.remove(sceDmacplusSc2MeSuspend);

        mm.remove(sceDmacplusSc2MeResume);

        mm.remove(sceDmacplusSc2MeNormal16);

        mm.remove(sceDmacplusSc2MeLLI);

        mm.remove(sceDmacplusSc2MeSync);

        mm.remove(sceDmacplusMe2ScInit);

        mm.remove(sceDmacplusMe2ScEnd);

        mm.remove(sceDmacplusMe2ScQuerySuspend);

        mm.remove(sceDmacplusMe2ScSuspend);

        mm.remove(sceDmacplusMe2ScResume);

        mm.remove(sceDmacplusMe2ScNormal16);

        mm.remove(sceDmacplusMe2ScLLI);

        mm.remove(sceDmacplusMe2ScSync);

        mm.remove(sceDmacplusSc128Init);

        mm.remove(sceDmacplusSc128End);

        mm.remove(sceDmacplusSc128QuerySuspend);

        mm.remove(sceDmacplusSc128Suspend);

        mm.remove(sceDmacplusSc128Resume);

        mm.remove(sceDmacplusSc128Memcpy);

        mm.remove(sceDmacplusSc128TryMemcpy);

        mm.remove(sceDmacplusSc128LLI);

    }
    public static final HLEModuleFunction sceDmacplusInit = new HLEModuleFunction("sceDmacplus_driver", "sceDmacplusInit") {

        @Override
        public void execute(Processor cpu, Memory mem) {
            System.out.println("Unimplement function sceDmacplusInit [0xDF32F547]");
        }
    };
    public static final HLEModuleFunction sceDmacplusEnd = new HLEModuleFunction("sceDmacplus_driver", "sceDmacplusEnd") {

        @Override
        public void execute(Processor cpu, Memory mem) {
            System.out.println("Unimplement function sceDmacplusEnd [0xE6219C61]");
        }
    };
    public static final HLEModuleFunction sceDmacplusQuerySuspend = new HLEModuleFunction("sceDmacplus_driver", "sceDmacplusQuerySuspend") {

        @Override
        public void execute(Processor cpu, Memory mem) {
            System.out.println("Unimplement function sceDmacplusQuerySuspend [0xC748491D]");
        }
    };
    public static final HLEModuleFunction sceDmacplusSuspend = new HLEModuleFunction("sceDmacplus_driver", "sceDmacplusSuspend") {

        @Override
        public void execute(Processor cpu, Memory mem) {
            System.out.println("Unimplement function sceDmacplusSuspend [0x853C5EC6]");
        }
    };
    public static final HLEModuleFunction sceDmacplusResume = new HLEModuleFunction("sceDmacplus_driver", "sceDmacplusResume") {

        @Override
        public void execute(Processor cpu, Memory mem) {
            System.out.println("Unimplement function sceDmacplusResume [0xD49A5922]");
        }
    };
    public static final HLEModuleFunction sceDmacplusEnableIntr = new HLEModuleFunction("sceDmacplus_driver", "sceDmacplusEnableIntr") {

        @Override
        public void execute(Processor cpu, Memory mem) {
            System.out.println("Unimplement function sceDmacplusEnableIntr [0xA7B05225]");
        }
    };
    public static final HLEModuleFunction sceDmacplusDisableIntr = new HLEModuleFunction("sceDmacplus_driver", "sceDmacplusDisableIntr") {

        @Override
        public void execute(Processor cpu, Memory mem) {
            System.out.println("Unimplement function sceDmacplusDisableIntr [0xBF939272]");
        }
    };
    public static final HLEModuleFunction sceDmacplusQueryIntr = new HLEModuleFunction("sceDmacplus_driver", "sceDmacplusQueryIntr") {

        @Override
        public void execute(Processor cpu, Memory mem) {
            System.out.println("Unimplement function sceDmacplusQueryIntr [0x6AA3D654]");
        }
    };
    public static final HLEModuleFunction sceDmacplusAcquireIntr = new HLEModuleFunction("sceDmacplus_driver", "sceDmacplusAcquireIntr") {

        @Override
        public void execute(Processor cpu, Memory mem) {
            System.out.println("Unimplement function sceDmacplusAcquireIntr [0x0DA570C1]");
        }
    };
    public static final HLEModuleFunction sceDmacplusLcdcInit = new HLEModuleFunction("sceDmacplus_driver", "sceDmacplusLcdcInit") {

        @Override
        public void execute(Processor cpu, Memory mem) {
            System.out.println("Unimplement function sceDmacplusLcdcInit [0xFE3F3228]");
        }
    };
    public static final HLEModuleFunction sceDmacplusLcdcEnd = new HLEModuleFunction("sceDmacplus_driver", "sceDmacplusLcdcEnd") {

        @Override
        public void execute(Processor cpu, Memory mem) {
            System.out.println("Unimplement function sceDmacplusLcdcEnd [0xCDB039A7]");
        }
    };
    public static final HLEModuleFunction sceDmacplusLcdcQuerySuspend = new HLEModuleFunction("sceDmacplus_driver", "sceDmacplusLcdcQuerySuspend") {

        @Override
        public void execute(Processor cpu, Memory mem) {
            System.out.println("Unimplement function sceDmacplusLcdcQuerySuspend [0xC3236D69]");
        }
    };
    public static final HLEModuleFunction sceDmacplusLcdcSuspend = new HLEModuleFunction("sceDmacplus_driver", "sceDmacplusLcdcSuspend") {

        @Override
        public void execute(Processor cpu, Memory mem) {
            System.out.println("Unimplement function sceDmacplusLcdcSuspend [0xC8336549]");
        }
    };
    public static final HLEModuleFunction sceDmacplusLcdcResume = new HLEModuleFunction("sceDmacplus_driver", "sceDmacplusLcdcResume") {

        @Override
        public void execute(Processor cpu, Memory mem) {
            System.out.println("Unimplement function sceDmacplusLcdcResume [0x42BEB349]");
        }
    };
    public static final HLEModuleFunction sceDmacplusLcdcSetBaseAddr = new HLEModuleFunction("sceDmacplus_driver", "sceDmacplusLcdcSetBaseAddr") {

        @Override
        public void execute(Processor cpu, Memory mem) {
            System.out.println("Unimplement function sceDmacplusLcdcSetBaseAddr [0x29B50A82]");
        }
    };
    public static final HLEModuleFunction sceDmacplusLcdcGetBaseAddr = new HLEModuleFunction("sceDmacplus_driver", "sceDmacplusLcdcGetBaseAddr") {

        @Override
        public void execute(Processor cpu, Memory mem) {
            System.out.println("Unimplement function sceDmacplusLcdcGetBaseAddr [0x58C380BB]");
        }
    };
    public static final HLEModuleFunction sceDmacplusLcdcSetFormat = new HLEModuleFunction("sceDmacplus_driver", "sceDmacplusLcdcSetFormat") {

        @Override
        public void execute(Processor cpu, Memory mem) {
            System.out.println("Unimplement function sceDmacplusLcdcSetFormat [0x8AE579CD]");
        }
    };
    public static final HLEModuleFunction sceDmacplusLcdcGetFormat = new HLEModuleFunction("sceDmacplus_driver", "sceDmacplusLcdcGetFormat") {

        @Override
        public void execute(Processor cpu, Memory mem) {
            System.out.println("Unimplement function sceDmacplusLcdcGetFormat [0x241601AE]");
        }
    };
    public static final HLEModuleFunction sceDmacplusLcdcEnable = new HLEModuleFunction("sceDmacplus_driver", "sceDmacplusLcdcEnable") {

        @Override
        public void execute(Processor cpu, Memory mem) {
            System.out.println("Unimplement function sceDmacplusLcdcEnable [0xF8C7C180]");
        }
    };
    public static final HLEModuleFunction sceDmacplusLcdcDisable = new HLEModuleFunction("sceDmacplus_driver", "sceDmacplusLcdcDisable") {

        @Override
        public void execute(Processor cpu, Memory mem) {
            System.out.println("Unimplement function sceDmacplusLcdcDisable [0x576522BC]");
        }
    };
    public static final HLEModuleFunction sceDmacplusAvcInit = new HLEModuleFunction("sceDmacplus_driver", "sceDmacplusAvcInit") {

        @Override
        public void execute(Processor cpu, Memory mem) {
            System.out.println("Unimplement function sceDmacplusAvcInit [0xBEC10779]");
        }
    };
    public static final HLEModuleFunction sceDmacplusAvcEnd = new HLEModuleFunction("sceDmacplus_driver", "sceDmacplusAvcEnd") {

        @Override
        public void execute(Processor cpu, Memory mem) {
            System.out.println("Unimplement function sceDmacplusAvcEnd [0x7AAE5443]");
        }
    };
    public static final HLEModuleFunction sceDmacplusAvcQuerySuspend = new HLEModuleFunction("sceDmacplus_driver", "sceDmacplusAvcQuerySuspend") {

        @Override
        public void execute(Processor cpu, Memory mem) {
            System.out.println("Unimplement function sceDmacplusAvcQuerySuspend [0x1E7483D0]");
        }
    };
    public static final HLEModuleFunction sceDmacplusAvcSuspend = new HLEModuleFunction("sceDmacplus_driver", "sceDmacplusAvcSuspend") {

        @Override
        public void execute(Processor cpu, Memory mem) {
            System.out.println("Unimplement function sceDmacplusAvcSuspend [0x168836CF]");
        }
    };
    public static final HLEModuleFunction sceDmacplusAvcResume = new HLEModuleFunction("sceDmacplus_driver", "sceDmacplusAvcResume") {

        @Override
        public void execute(Processor cpu, Memory mem) {
            System.out.println("Unimplement function sceDmacplusAvcResume [0x5E32C8AF]");
        }
    };
    public static final HLEModuleFunction sceDmacplus_driver_B2EFA681 = new HLEModuleFunction("sceDmacplus_driver", "sceDmacplus_driver_B2EFA681") {

        @Override
        public void execute(Processor cpu, Memory mem) {
            System.out.println("Unimplement function sceDmacplus_driver_B2EFA681 [0xB2EFA681]");
        }
    };
    public static final HLEModuleFunction sceDmacplus_driver_1D73DDA8 = new HLEModuleFunction("sceDmacplus_driver", "sceDmacplus_driver_1D73DDA8") {

        @Override
        public void execute(Processor cpu, Memory mem) {
            System.out.println("Unimplement function sceDmacplus_driver_1D73DDA8 [0x1D73DDA8]");
        }
    };
    public static final HLEModuleFunction sceDmacplus_driver_74323807 = new HLEModuleFunction("sceDmacplus_driver", "sceDmacplus_driver_74323807") {

        @Override
        public void execute(Processor cpu, Memory mem) {
            System.out.println("Unimplement function sceDmacplus_driver_74323807 [0x74323807]");
        }
    };
    public static final HLEModuleFunction sceDmacplusAvcSync = new HLEModuleFunction("sceDmacplus_driver", "sceDmacplusAvcSync") {

        @Override
        public void execute(Processor cpu, Memory mem) {
            System.out.println("Unimplement function sceDmacplusAvcSync [0x3A98EE05]");
        }
    };
    public static final HLEModuleFunction sceDmacplusSc2MeInit = new HLEModuleFunction("sceDmacplus_driver", "sceDmacplusSc2MeInit") {

        @Override
        public void execute(Processor cpu, Memory mem) {
            System.out.println("Unimplement function sceDmacplusSc2MeInit [0xFD8B15BC]");
        }
    };
    public static final HLEModuleFunction sceDmacplusSc2MeEnd = new HLEModuleFunction("sceDmacplus_driver", "sceDmacplusSc2MeEnd") {

        @Override
        public void execute(Processor cpu, Memory mem) {
            System.out.println("Unimplement function sceDmacplusSc2MeEnd [0xF7DEC189]");
        }
    };
    public static final HLEModuleFunction sceDmacplusSc2MeQuerySuspend = new HLEModuleFunction("sceDmacplus_driver", "sceDmacplusSc2MeQuerySuspend") {

        @Override
        public void execute(Processor cpu, Memory mem) {
            System.out.println("Unimplement function sceDmacplusSc2MeQuerySuspend [0xD0464B29]");
        }
    };
    public static final HLEModuleFunction sceDmacplusSc2MeSuspend = new HLEModuleFunction("sceDmacplus_driver", "sceDmacplusSc2MeSuspend") {

        @Override
        public void execute(Processor cpu, Memory mem) {
            System.out.println("Unimplement function sceDmacplusSc2MeSuspend [0xFEE3392C]");
        }
    };
    public static final HLEModuleFunction sceDmacplusSc2MeResume = new HLEModuleFunction("sceDmacplus_driver", "sceDmacplusSc2MeResume") {

        @Override
        public void execute(Processor cpu, Memory mem) {
            System.out.println("Unimplement function sceDmacplusSc2MeResume [0xC5B75E09]");
        }
    };
    public static final HLEModuleFunction sceDmacplusSc2MeNormal16 = new HLEModuleFunction("sceDmacplus_driver", "sceDmacplusSc2MeNormal16") {

        @Override
        public void execute(Processor cpu, Memory mem) {
            System.out.println("Unimplement function sceDmacplusSc2MeNormal16 [0x4B980588]");
        }
    };
    public static final HLEModuleFunction sceDmacplusSc2MeLLI = new HLEModuleFunction("sceDmacplus_driver", "sceDmacplusSc2MeLLI") {

        @Override
        public void execute(Processor cpu, Memory mem) {
            System.out.println("Unimplement function sceDmacplusSc2MeLLI [0x3438DA0B]");
        }
    };
    public static final HLEModuleFunction sceDmacplusSc2MeSync = new HLEModuleFunction("sceDmacplus_driver", "sceDmacplusSc2MeSync") {

        @Override
        public void execute(Processor cpu, Memory mem) {
            System.out.println("Unimplement function sceDmacplusSc2MeSync [0x58DE4914]");
        }
    };
    public static final HLEModuleFunction sceDmacplusMe2ScInit = new HLEModuleFunction("sceDmacplus_driver", "sceDmacplusMe2ScInit") {

        @Override
        public void execute(Processor cpu, Memory mem) {
            System.out.println("Unimplement function sceDmacplusMe2ScInit [0x1F5A80D0]");
        }
    };
    public static final HLEModuleFunction sceDmacplusMe2ScEnd = new HLEModuleFunction("sceDmacplus_driver", "sceDmacplusMe2ScEnd") {

        @Override
        public void execute(Processor cpu, Memory mem) {
            System.out.println("Unimplement function sceDmacplusMe2ScEnd [0xD1E1567E]");
        }
    };
    public static final HLEModuleFunction sceDmacplusMe2ScQuerySuspend = new HLEModuleFunction("sceDmacplus_driver", "sceDmacplusMe2ScQuerySuspend") {

        @Override
        public void execute(Processor cpu, Memory mem) {
            System.out.println("Unimplement function sceDmacplusMe2ScQuerySuspend [0x9393B40D]");
        }
    };
    public static final HLEModuleFunction sceDmacplusMe2ScSuspend = new HLEModuleFunction("sceDmacplus_driver", "sceDmacplusMe2ScSuspend") {

        @Override
        public void execute(Processor cpu, Memory mem) {
            System.out.println("Unimplement function sceDmacplusMe2ScSuspend [0x6D4F8BD7]");
        }
    };
    public static final HLEModuleFunction sceDmacplusMe2ScResume = new HLEModuleFunction("sceDmacplus_driver", "sceDmacplusMe2ScResume") {

        @Override
        public void execute(Processor cpu, Memory mem) {
            System.out.println("Unimplement function sceDmacplusMe2ScResume [0x78A55D62]");
        }
    };
    public static final HLEModuleFunction sceDmacplusMe2ScNormal16 = new HLEModuleFunction("sceDmacplus_driver", "sceDmacplusMe2ScNormal16") {

        @Override
        public void execute(Processor cpu, Memory mem) {
            System.out.println("Unimplement function sceDmacplusMe2ScNormal16 [0xBE693828]");
        }
    };
    public static final HLEModuleFunction sceDmacplusMe2ScLLI = new HLEModuleFunction("sceDmacplus_driver", "sceDmacplusMe2ScLLI") {

        @Override
        public void execute(Processor cpu, Memory mem) {
            System.out.println("Unimplement function sceDmacplusMe2ScLLI [0x2D5940FF]");
        }
    };
    public static final HLEModuleFunction sceDmacplusMe2ScSync = new HLEModuleFunction("sceDmacplus_driver", "sceDmacplusMe2ScSync") {

        @Override
        public void execute(Processor cpu, Memory mem) {
            System.out.println("Unimplement function sceDmacplusMe2ScSync [0xAB49D2CB]");
        }
    };
    public static final HLEModuleFunction sceDmacplusSc128Init = new HLEModuleFunction("sceDmacplus_driver", "sceDmacplusSc128Init") {

        @Override
        public void execute(Processor cpu, Memory mem) {
            System.out.println("Unimplement function sceDmacplusSc128Init [0xB6592A56]");
        }
    };
    public static final HLEModuleFunction sceDmacplusSc128End = new HLEModuleFunction("sceDmacplus_driver", "sceDmacplusSc128End") {

        @Override
        public void execute(Processor cpu, Memory mem) {
            System.out.println("Unimplement function sceDmacplusSc128End [0x4F1B8D26]");
        }
    };
    public static final HLEModuleFunction sceDmacplusSc128QuerySuspend = new HLEModuleFunction("sceDmacplus_driver", "sceDmacplusSc128QuerySuspend") {

        @Override
        public void execute(Processor cpu, Memory mem) {
            System.out.println("Unimplement function sceDmacplusSc128QuerySuspend [0x410ED0DD]");
        }
    };
    public static final HLEModuleFunction sceDmacplusSc128Suspend = new HLEModuleFunction("sceDmacplus_driver", "sceDmacplusSc128Suspend") {

        @Override
        public void execute(Processor cpu, Memory mem) {
            System.out.println("Unimplement function sceDmacplusSc128Suspend [0x3DB353DB]");
        }
    };
    public static final HLEModuleFunction sceDmacplusSc128Resume = new HLEModuleFunction("sceDmacplus_driver", "sceDmacplusSc128Resume") {

        @Override
        public void execute(Processor cpu, Memory mem) {
            System.out.println("Unimplement function sceDmacplusSc128Resume [0x97DCBBBF]");
        }
    };
    public static final HLEModuleFunction sceDmacplusSc128Memcpy = new HLEModuleFunction("sceDmacplus_driver", "sceDmacplusSc128Memcpy") {

        @Override
        public void execute(Processor cpu, Memory mem) {
            System.out.println("Unimplement function sceDmacplusSc128Memcpy [0xC7D33466]");
        }
    };
    public static final HLEModuleFunction sceDmacplusSc128TryMemcpy = new HLEModuleFunction("sceDmacplus_driver", "sceDmacplusSc128TryMemcpy") {

        @Override
        public void execute(Processor cpu, Memory mem) {
            System.out.println("Unimplement function sceDmacplusSc128TryMemcpy [0x28558DBF]");
        }
    };
    public static final HLEModuleFunction sceDmacplusSc128LLI = new HLEModuleFunction("sceDmacplus_driver", "sceDmacplusSc128LLI") {

        @Override
        public void execute(Processor cpu, Memory mem) {
            System.out.println("Unimplement function sceDmacplusSc128LLI [0xFD183BCF]");
        }
    };
};
