/* This autogenerated file is part of jpcsp. */
package jpcsp.HLE.modules;

import jpcsp.HLE.pspSysMem;
import jpcsp.Memory;
import jpcsp.Processor;

public class sceImpose_driver implements HLEModule {

    @Override
    public final String getName() {
        return "sceImpose_driver";
    }

    @Override
    public void installModule(HLEModuleManager mm, int version) {

        mm.add(sceImposeInit, 0xBDBC42A6);

        mm.add(sceImposeEnd, 0xC7E36CC7);

        mm.add(sceImposeSuspend, 0x1AEED8FE);

        mm.add(sceImposeResume, 0x86924032);

        mm.add(sceImposeGetStatus, 0x1B6E3400);

        mm.add(sceImposeSetStatus, 0x9C8C6C81);

        mm.add(sceImposeGetParam, 0x531C9778);

        mm.add(sceImposeSetParam, 0x810FB7FB);

        mm.add(sceImposeChanges, 0xB415FC59);

        mm.add(sceImposeHomeButton, 0x381BD9E7);

        mm.add(sceImposeSetHomePopup, 0x5595A71A);

        mm.add(sceImposeGetHomePopup, 0x0F341BE4);

        mm.add(sceImposeSetUMDPopup, 0x72189C48);

        mm.add(sceImposeGetUMDPopup, 0xE0887BC8);

        mm.add(sceImposeSetLanguageMode, 0x36AA6E91);

        mm.add(sceImposeGetLanguageMode, 0x24FD7BCF);

        mm.add(sceImposeGetBatteryIconStatus, 0x8C943191);

    }

    @Override
    public void uninstallModule(HLEModuleManager mm, int version) {

        mm.remove(sceImposeInit);

        mm.remove(sceImposeEnd);

        mm.remove(sceImposeSuspend);

        mm.remove(sceImposeResume);

        mm.remove(sceImposeGetStatus);

        mm.remove(sceImposeSetStatus);

        mm.remove(sceImposeGetParam);

        mm.remove(sceImposeSetParam);

        mm.remove(sceImposeChanges);

        mm.remove(sceImposeHomeButton);

        mm.remove(sceImposeSetHomePopup);

        mm.remove(sceImposeGetHomePopup);

        mm.remove(sceImposeSetUMDPopup);

        mm.remove(sceImposeGetUMDPopup);

        mm.remove(sceImposeSetLanguageMode);

        mm.remove(sceImposeGetLanguageMode);

        mm.remove(sceImposeGetBatteryIconStatus);

    }
    public static final HLEModuleFunction sceImposeInit = new HLEModuleFunction("sceImpose_driver", "sceImposeInit") {

        @Override
        public void execute(Processor cpu, Memory mem) {
            System.out.println("Unimplement function sceImposeInit [0xBDBC42A6]");
        }
    };
    public static final HLEModuleFunction sceImposeEnd = new HLEModuleFunction("sceImpose_driver", "sceImposeEnd") {

        @Override
        public void execute(Processor cpu, Memory mem) {
            System.out.println("Unimplement function sceImposeEnd [0xC7E36CC7]");
        }
    };
    public static final HLEModuleFunction sceImposeSuspend = new HLEModuleFunction("sceImpose_driver", "sceImposeSuspend") {

        @Override
        public void execute(Processor cpu, Memory mem) {
            System.out.println("Unimplement function sceImposeSuspend [0x1AEED8FE]");
        }
    };
    public static final HLEModuleFunction sceImposeResume = new HLEModuleFunction("sceImpose_driver", "sceImposeResume") {

        @Override
        public void execute(Processor cpu, Memory mem) {
            System.out.println("Unimplement function sceImposeResume [0x86924032]");
        }
    };
    public static final HLEModuleFunction sceImposeGetStatus = new HLEModuleFunction("sceImpose_driver", "sceImposeGetStatus") {

        @Override
        public void execute(Processor cpu, Memory mem) {
            System.out.println("Unimplement function sceImposeGetStatus [0x1B6E3400]");
        }
    };
    public static final HLEModuleFunction sceImposeSetStatus = new HLEModuleFunction("sceImpose_driver", "sceImposeSetStatus") {

        @Override
        public void execute(Processor cpu, Memory mem) {
            System.out.println("Unimplement function sceImposeSetStatus [0x9C8C6C81]");
        }
    };
    public static final HLEModuleFunction sceImposeGetParam = new HLEModuleFunction("sceImpose_driver", "sceImposeGetParam") {

        @Override
        public void execute(Processor cpu, Memory mem) {
            System.out.println("Unimplement function sceImposeGetParam [0x531C9778]");
        }
    };
    public static final HLEModuleFunction sceImposeSetParam = new HLEModuleFunction("sceImpose_driver", "sceImposeSetParam") {

        @Override
        public void execute(Processor cpu, Memory mem) {
            System.out.println("Unimplement function sceImposeSetParam [0x810FB7FB]");
        }
    };
    public static final HLEModuleFunction sceImposeChanges = new HLEModuleFunction("sceImpose_driver", "sceImposeChanges") {

        @Override
        public void execute(Processor cpu, Memory mem) {
            System.out.println("Unimplement function sceImposeChanges [0xB415FC59]");
        }
    };
    public static final HLEModuleFunction sceImposeHomeButton = new HLEModuleFunction("sceImpose_driver", "sceImposeHomeButton") {

        @Override
        public void execute(Processor cpu, Memory mem) {
            System.out.println("Unimplement function sceImposeHomeButton [0x381BD9E7]");
        }
    };
    public static final HLEModuleFunction sceImposeSetHomePopup = new HLEModuleFunction("sceImpose_driver", "sceImposeSetHomePopup") {

        @Override
        public void execute(Processor cpu, Memory mem) {
            System.out.println("Unimplement function sceImposeSetHomePopup [0x5595A71A]");
        }
    };
    public static final HLEModuleFunction sceImposeGetHomePopup = new HLEModuleFunction("sceImpose_driver", "sceImposeGetHomePopup") {

        @Override
        public void execute(Processor cpu, Memory mem) {
            System.out.println("Unimplement function sceImposeGetHomePopup [0x0F341BE4]");
        }
    };
    public static final HLEModuleFunction sceImposeSetUMDPopup = new HLEModuleFunction("sceImpose_driver", "sceImposeSetUMDPopup") {

        @Override
        public void execute(Processor cpu, Memory mem) {
            System.out.println("Unimplement function sceImposeSetUMDPopup [0x72189C48]");
        }
    };
    public static final HLEModuleFunction sceImposeGetUMDPopup = new HLEModuleFunction("sceImpose_driver", "sceImposeGetUMDPopup") {

        @Override
        public void execute(Processor cpu, Memory mem) {
            System.out.println("Unimplement function sceImposeGetUMDPopup [0xE0887BC8]");
        }
    };
    public static final HLEModuleFunction sceImposeSetLanguageMode = new HLEModuleFunction("sceImpose_driver", "sceImposeSetLanguageMode") {

        @Override
        public void execute(Processor cpu, Memory mem) {
            System.out.println("Unimplement function sceImposeSetLanguageMode [0x36AA6E91]");
        }
    };
    public static final HLEModuleFunction sceImposeGetLanguageMode = new HLEModuleFunction("sceImpose_driver", "sceImposeGetLanguageMode") {

        @Override
        public void execute(Processor cpu, Memory mem) {
            System.out.println("Unimplement function sceImposeGetLanguageMode [0x24FD7BCF]");
        }
    };
    public static final HLEModuleFunction sceImposeGetBatteryIconStatus = new HLEModuleFunction("sceImpose_driver", "sceImposeGetBatteryIconStatus") {

        @Override
        public void execute(Processor cpu, Memory mem) {
            System.out.println("Unimplement function sceImposeGetBatteryIconStatus [0x8C943191]");
        }
    };
};
