/* This autogenerated file is part of jpcsp. */
package jpcsp.HLE.modules;

import jpcsp.HLE.pspSysMem;
import jpcsp.Memory;
import jpcsp.Processor;

public class sceMeVideo_driver implements HLEModule {

    @Override
    public final String getName() {
        return "sceMeVideo_driver";
    }

    @Override
    public void installModule(HLEModuleManager mm, int version) {

        mm.add(sceMeVideo_driver_B655AD4E, 0xB655AD4E);

        mm.add(sceMeVideo_driver_06F0236A, 0x06F0236A);

        mm.add(sceMeVideo_driver_176BBE07, 0x176BBE07);

        mm.add(sceMeVideo_driver_DE2E7E89, 0xDE2E7E89);

        mm.add(sceMeVideo_driver_E67F4E0A, 0xE67F4E0A);

        mm.add(sceMeVideo_driver_1C6A60E1, 0x1C6A60E1);

    }

    @Override
    public void uninstallModule(HLEModuleManager mm, int version) {

        mm.remove(sceMeVideo_driver_B655AD4E);

        mm.remove(sceMeVideo_driver_06F0236A);

        mm.remove(sceMeVideo_driver_176BBE07);

        mm.remove(sceMeVideo_driver_DE2E7E89);

        mm.remove(sceMeVideo_driver_E67F4E0A);

        mm.remove(sceMeVideo_driver_1C6A60E1);

    }
    public static final HLEModuleFunction sceMeVideo_driver_B655AD4E = new HLEModuleFunction("sceMeVideo_driver", "sceMeVideo_driver_B655AD4E") {

        @Override
        public void execute(Processor cpu, Memory mem) {
            System.out.println("Unimplement function sceMeVideo_driver_B655AD4E [0xB655AD4E]");
        }
    };
    public static final HLEModuleFunction sceMeVideo_driver_06F0236A = new HLEModuleFunction("sceMeVideo_driver", "sceMeVideo_driver_06F0236A") {

        @Override
        public void execute(Processor cpu, Memory mem) {
            System.out.println("Unimplement function sceMeVideo_driver_06F0236A [0x06F0236A]");
        }
    };
    public static final HLEModuleFunction sceMeVideo_driver_176BBE07 = new HLEModuleFunction("sceMeVideo_driver", "sceMeVideo_driver_176BBE07") {

        @Override
        public void execute(Processor cpu, Memory mem) {
            System.out.println("Unimplement function sceMeVideo_driver_176BBE07 [0x176BBE07]");
        }
    };
    public static final HLEModuleFunction sceMeVideo_driver_DE2E7E89 = new HLEModuleFunction("sceMeVideo_driver", "sceMeVideo_driver_DE2E7E89") {

        @Override
        public void execute(Processor cpu, Memory mem) {
            System.out.println("Unimplement function sceMeVideo_driver_DE2E7E89 [0xDE2E7E89]");
        }
    };
    public static final HLEModuleFunction sceMeVideo_driver_E67F4E0A = new HLEModuleFunction("sceMeVideo_driver", "sceMeVideo_driver_E67F4E0A") {

        @Override
        public void execute(Processor cpu, Memory mem) {
            System.out.println("Unimplement function sceMeVideo_driver_E67F4E0A [0xE67F4E0A]");
        }
    };
    public static final HLEModuleFunction sceMeVideo_driver_1C6A60E1 = new HLEModuleFunction("sceMeVideo_driver", "sceMeVideo_driver_1C6A60E1") {

        @Override
        public void execute(Processor cpu, Memory mem) {
            System.out.println("Unimplement function sceMeVideo_driver_1C6A60E1 [0x1C6A60E1]");
        }
    };
};
