/* This autogenerated file is part of jpcsp. */
package jpcsp.HLE.modules;

import jpcsp.HLE.pspSysMem;
import jpcsp.Memory;
import jpcsp.Processor;

public class sceMemab_driver implements HLEModule {

    @Override
    public final String getName() {
        return "sceMemab_driver";
    }

    @Override
    public void installModule(HLEModuleManager mm, int version) {

        mm.add(sceMemab_driver_01FD1BA0, 0x01FD1BA0);

        mm.add(sceMemab_driver_0C134D3F, 0x0C134D3F);

        mm.add(sceMemab_driver_A4720EED, 0xA4720EED);

        mm.add(sceMemab_driver_DC598EF3, 0xDC598EF3);

        mm.add(sceMemab_driver_8DAC2343, 0x8DAC2343);

        mm.add(sceMemab_driver_DAE8A629, 0xDAE8A629);

        mm.add(sceMemab_driver_CF49BCBB, 0xCF49BCBB);

        mm.add(sceMemab_driver_E6D3ACE2, 0xE6D3ACE2);

        mm.add(sceMemab_driver_B54E1AA7, 0xB54E1AA7);

        mm.add(sceMemab_driver_F1D2B9B0, 0xF1D2B9B0);

        mm.add(sceMemab_driver_4DF566D3, 0x4DF566D3);

        mm.add(sceMemab_driver_F94CA9B8, 0xF94CA9B8);

        mm.add(sceMemab_driver_34EBFB6A, 0x34EBFB6A);

        mm.add(sceMemab_driver_531E144B, 0x531E144B);

    }

    @Override
    public void uninstallModule(HLEModuleManager mm, int version) {

        mm.remove(sceMemab_driver_01FD1BA0);

        mm.remove(sceMemab_driver_0C134D3F);

        mm.remove(sceMemab_driver_A4720EED);

        mm.remove(sceMemab_driver_DC598EF3);

        mm.remove(sceMemab_driver_8DAC2343);

        mm.remove(sceMemab_driver_DAE8A629);

        mm.remove(sceMemab_driver_CF49BCBB);

        mm.remove(sceMemab_driver_E6D3ACE2);

        mm.remove(sceMemab_driver_B54E1AA7);

        mm.remove(sceMemab_driver_F1D2B9B0);

        mm.remove(sceMemab_driver_4DF566D3);

        mm.remove(sceMemab_driver_F94CA9B8);

        mm.remove(sceMemab_driver_34EBFB6A);

        mm.remove(sceMemab_driver_531E144B);

    }
    public static final HLEModuleFunction sceMemab_driver_01FD1BA0 = new HLEModuleFunction("sceMemab_driver", "sceMemab_driver_01FD1BA0") {

        @Override
        public void execute(Processor cpu, Memory mem) {
            System.out.println("Unimplement function sceMemab_driver_01FD1BA0 [0x01FD1BA0]");
        }
    };
    public static final HLEModuleFunction sceMemab_driver_0C134D3F = new HLEModuleFunction("sceMemab_driver", "sceMemab_driver_0C134D3F") {

        @Override
        public void execute(Processor cpu, Memory mem) {
            System.out.println("Unimplement function sceMemab_driver_0C134D3F [0x0C134D3F]");
        }
    };
    public static final HLEModuleFunction sceMemab_driver_A4720EED = new HLEModuleFunction("sceMemab_driver", "sceMemab_driver_A4720EED") {

        @Override
        public void execute(Processor cpu, Memory mem) {
            System.out.println("Unimplement function sceMemab_driver_A4720EED [0xA4720EED]");
        }
    };
    public static final HLEModuleFunction sceMemab_driver_DC598EF3 = new HLEModuleFunction("sceMemab_driver", "sceMemab_driver_DC598EF3") {

        @Override
        public void execute(Processor cpu, Memory mem) {
            System.out.println("Unimplement function sceMemab_driver_DC598EF3 [0xDC598EF3]");
        }
    };
    public static final HLEModuleFunction sceMemab_driver_8DAC2343 = new HLEModuleFunction("sceMemab_driver", "sceMemab_driver_8DAC2343") {

        @Override
        public void execute(Processor cpu, Memory mem) {
            System.out.println("Unimplement function sceMemab_driver_8DAC2343 [0x8DAC2343]");
        }
    };
    public static final HLEModuleFunction sceMemab_driver_DAE8A629 = new HLEModuleFunction("sceMemab_driver", "sceMemab_driver_DAE8A629") {

        @Override
        public void execute(Processor cpu, Memory mem) {
            System.out.println("Unimplement function sceMemab_driver_DAE8A629 [0xDAE8A629]");
        }
    };
    public static final HLEModuleFunction sceMemab_driver_CF49BCBB = new HLEModuleFunction("sceMemab_driver", "sceMemab_driver_CF49BCBB") {

        @Override
        public void execute(Processor cpu, Memory mem) {
            System.out.println("Unimplement function sceMemab_driver_CF49BCBB [0xCF49BCBB]");
        }
    };
    public static final HLEModuleFunction sceMemab_driver_E6D3ACE2 = new HLEModuleFunction("sceMemab_driver", "sceMemab_driver_E6D3ACE2") {

        @Override
        public void execute(Processor cpu, Memory mem) {
            System.out.println("Unimplement function sceMemab_driver_E6D3ACE2 [0xE6D3ACE2]");
        }
    };
    public static final HLEModuleFunction sceMemab_driver_B54E1AA7 = new HLEModuleFunction("sceMemab_driver", "sceMemab_driver_B54E1AA7") {

        @Override
        public void execute(Processor cpu, Memory mem) {
            System.out.println("Unimplement function sceMemab_driver_B54E1AA7 [0xB54E1AA7]");
        }
    };
    public static final HLEModuleFunction sceMemab_driver_F1D2B9B0 = new HLEModuleFunction("sceMemab_driver", "sceMemab_driver_F1D2B9B0") {

        @Override
        public void execute(Processor cpu, Memory mem) {
            System.out.println("Unimplement function sceMemab_driver_F1D2B9B0 [0xF1D2B9B0]");
        }
    };
    public static final HLEModuleFunction sceMemab_driver_4DF566D3 = new HLEModuleFunction("sceMemab_driver", "sceMemab_driver_4DF566D3") {

        @Override
        public void execute(Processor cpu, Memory mem) {
            System.out.println("Unimplement function sceMemab_driver_4DF566D3 [0x4DF566D3]");
        }
    };
    public static final HLEModuleFunction sceMemab_driver_F94CA9B8 = new HLEModuleFunction("sceMemab_driver", "sceMemab_driver_F94CA9B8") {

        @Override
        public void execute(Processor cpu, Memory mem) {
            System.out.println("Unimplement function sceMemab_driver_F94CA9B8 [0xF94CA9B8]");
        }
    };
    public static final HLEModuleFunction sceMemab_driver_34EBFB6A = new HLEModuleFunction("sceMemab_driver", "sceMemab_driver_34EBFB6A") {

        @Override
        public void execute(Processor cpu, Memory mem) {
            System.out.println("Unimplement function sceMemab_driver_34EBFB6A [0x34EBFB6A]");
        }
    };
    public static final HLEModuleFunction sceMemab_driver_531E144B = new HLEModuleFunction("sceMemab_driver", "sceMemab_driver_531E144B") {

        @Override
        public void execute(Processor cpu, Memory mem) {
            System.out.println("Unimplement function sceMemab_driver_531E144B [0x531E144B]");
        }
    };
};
