/* This autogenerated file is part of jpcsp. */
package jpcsp.HLE.modules;

import jpcsp.HLE.pspSysMem;
import jpcsp.Memory;
import jpcsp.Processor;

public class sceNetIfhandle_driver implements HLEModule {

    @Override
    public final String getName() {
        return "sceNetIfhandle_driver";
    }

    @Override
    public void installModule(HLEModuleManager mm, int version) {

        mm.add(sceNetIfhandleInit, 0x30F69334);

        mm.add(sceNetIfhandleTerm, 0xB9096E48);

        mm.add(sceNetIfhandleGetAttachEther, 0xB8188F96);

        mm.add(sceNetIfhandleGetDetachEther, 0x4FB43BCE);

        mm.add(sceNetIfhandleIfStart, 0xB1F5BB87);

        mm.add(sceNetIfhandleIfUp, 0x8FCB05A1);

        mm.add(sceNetIfhandleIfDown, 0xEAD3A759);

        mm.add(sceNetIfhandleIfIoctl, 0x0296C7D6);

        mm.add(sceNetIfhandleIfDequeue, 0xE440A7D8);

        mm.add(sceNetIfhandleSignalSema, 0x30602CE9);

        mm.add(sceNetIfhandleWaitSema, 0xD5DA7B3C);

        mm.add(sceNetIfhandlePollSema, 0x2162EE67);

        mm.add(sceNetCreateIfhandleEther, 0x16042084);

        mm.add(sceNetDestroyIfhandleEther, 0xC9344A59);

        mm.add(sceNetAttachIfhandleEther, 0xAE81C0CB);

        mm.add(sceNetDetachIfhandleEther, 0x54D1AEA1);

        mm.add(sceNetSendIfEvent, 0xF94BAF52);

        mm.add(sceNetFlagIfEvent, 0x263767F6);

        mm.add(sceNetIfDequeue, 0xE2F4F1C9);

        mm.add(sceNetIfEnqueue, 0xC28F6FF2);

        mm.add(sceNetIfPrepend, 0x16246B99);

        mm.add(sceNetIfhandle_driver_C6D14282, 0xC6D14282);

        mm.add(sceNetIfhandle_driver_D5AD6DEA, 0xD5AD6DEA);

        mm.add(sceNetIfhandle_driver_0C391E9F, 0x0C391E9F);

        mm.add(sceNetIfhandle_driver_29ED84C5, 0x29ED84C5);

        mm.add(sceNetMallocInternal, 0x15CFE3C0);

        mm.add(sceNetFreeInternal, 0x76BAD213);

        mm.add(sceNetGetMallocStatInternal, 0x4C2886CB);

        mm.add(sceNetIfhandle_driver_0FB8AE0D, 0x0FB8AE0D);

        mm.add(sceNetIfhandle_driver_5FB31C72, 0x5FB31C72);

        mm.add(sceNetIfhandle_driver_62B20015, 0x62B20015);

        mm.add(sceNetMAdj, 0xBFF3CEA5);

        mm.add(sceNetMCat, 0x3E8DD3F8);

        mm.add(sceNetMCopyback, 0x1560F143);

        mm.add(sceNetMCopydata, 0x9A6261EC);

        mm.add(sceNetMCopym, 0x456E3146);

        mm.add(sceNetIfhandle_driver_955F2924, 0x955F2924);

        mm.add(sceNetMDup, 0x6AB53C27);

        mm.add(sceNetMFree, 0xF8825DC4);

        mm.add(sceNetMFreem, 0xF56FAC82);

        mm.add(sceNetMGet, 0xA493AA5F);

        mm.add(sceNetMGetclr, 0x59F0D619);

        mm.add(sceNetMGethdr, 0x4CF15C43);

        mm.add(sceNetMPrepend, 0xC3325FDC);

        mm.add(sceNetMPulldown, 0xE80F00A4);

        mm.add(sceNetMPullup, 0x49EDBB18);

        mm.add(sceNetIfhandle_driver_0542835F, 0x0542835F);

        mm.add(sceNetIfhandle_driver_773FC77C, 0x773FC77C);

        mm.add(sceNetIfhandle_driver_9CBA24D4, 0x9CBA24D4);

        mm.add(sceNetIfhandle_driver_C5623112, 0xC5623112);

        mm.add(sceNetGetDropRate, 0xC80181A2);

        mm.add(sceNetSetDropRate, 0xFD8585E1);

    }

    @Override
    public void uninstallModule(HLEModuleManager mm, int version) {

        mm.remove(sceNetIfhandleInit);

        mm.remove(sceNetIfhandleTerm);

        mm.remove(sceNetIfhandleGetAttachEther);

        mm.remove(sceNetIfhandleGetDetachEther);

        mm.remove(sceNetIfhandleIfStart);

        mm.remove(sceNetIfhandleIfUp);

        mm.remove(sceNetIfhandleIfDown);

        mm.remove(sceNetIfhandleIfIoctl);

        mm.remove(sceNetIfhandleIfDequeue);

        mm.remove(sceNetIfhandleSignalSema);

        mm.remove(sceNetIfhandleWaitSema);

        mm.remove(sceNetIfhandlePollSema);

        mm.remove(sceNetCreateIfhandleEther);

        mm.remove(sceNetDestroyIfhandleEther);

        mm.remove(sceNetAttachIfhandleEther);

        mm.remove(sceNetDetachIfhandleEther);

        mm.remove(sceNetSendIfEvent);

        mm.remove(sceNetFlagIfEvent);

        mm.remove(sceNetIfDequeue);

        mm.remove(sceNetIfEnqueue);

        mm.remove(sceNetIfPrepend);

        mm.remove(sceNetIfhandle_driver_C6D14282);

        mm.remove(sceNetIfhandle_driver_D5AD6DEA);

        mm.remove(sceNetIfhandle_driver_0C391E9F);

        mm.remove(sceNetIfhandle_driver_29ED84C5);

        mm.remove(sceNetMallocInternal);

        mm.remove(sceNetFreeInternal);

        mm.remove(sceNetGetMallocStatInternal);

        mm.remove(sceNetIfhandle_driver_0FB8AE0D);

        mm.remove(sceNetIfhandle_driver_5FB31C72);

        mm.remove(sceNetIfhandle_driver_62B20015);

        mm.remove(sceNetMAdj);

        mm.remove(sceNetMCat);

        mm.remove(sceNetMCopyback);

        mm.remove(sceNetMCopydata);

        mm.remove(sceNetMCopym);

        mm.remove(sceNetIfhandle_driver_955F2924);

        mm.remove(sceNetMDup);

        mm.remove(sceNetMFree);

        mm.remove(sceNetMFreem);

        mm.remove(sceNetMGet);

        mm.remove(sceNetMGetclr);

        mm.remove(sceNetMGethdr);

        mm.remove(sceNetMPrepend);

        mm.remove(sceNetMPulldown);

        mm.remove(sceNetMPullup);

        mm.remove(sceNetIfhandle_driver_0542835F);

        mm.remove(sceNetIfhandle_driver_773FC77C);

        mm.remove(sceNetIfhandle_driver_9CBA24D4);

        mm.remove(sceNetIfhandle_driver_C5623112);

        mm.remove(sceNetGetDropRate);

        mm.remove(sceNetSetDropRate);

    }
    public static final HLEModuleFunction sceNetIfhandleInit = new HLEModuleFunction("sceNetIfhandle_driver", "sceNetIfhandleInit") {

        @Override
        public void execute(Processor cpu, Memory mem) {
            System.out.println("Unimplement function sceNetIfhandleInit [0x30F69334]");
        }
    };
    public static final HLEModuleFunction sceNetIfhandleTerm = new HLEModuleFunction("sceNetIfhandle_driver", "sceNetIfhandleTerm") {

        @Override
        public void execute(Processor cpu, Memory mem) {
            System.out.println("Unimplement function sceNetIfhandleTerm [0xB9096E48]");
        }
    };
    public static final HLEModuleFunction sceNetIfhandleGetAttachEther = new HLEModuleFunction("sceNetIfhandle_driver", "sceNetIfhandleGetAttachEther") {

        @Override
        public void execute(Processor cpu, Memory mem) {
            System.out.println("Unimplement function sceNetIfhandleGetAttachEther [0xB8188F96]");
        }
    };
    public static final HLEModuleFunction sceNetIfhandleGetDetachEther = new HLEModuleFunction("sceNetIfhandle_driver", "sceNetIfhandleGetDetachEther") {

        @Override
        public void execute(Processor cpu, Memory mem) {
            System.out.println("Unimplement function sceNetIfhandleGetDetachEther [0x4FB43BCE]");
        }
    };
    public static final HLEModuleFunction sceNetIfhandleIfStart = new HLEModuleFunction("sceNetIfhandle_driver", "sceNetIfhandleIfStart") {

        @Override
        public void execute(Processor cpu, Memory mem) {
            System.out.println("Unimplement function sceNetIfhandleIfStart [0xB1F5BB87]");
        }
    };
    public static final HLEModuleFunction sceNetIfhandleIfUp = new HLEModuleFunction("sceNetIfhandle_driver", "sceNetIfhandleIfUp") {

        @Override
        public void execute(Processor cpu, Memory mem) {
            System.out.println("Unimplement function sceNetIfhandleIfUp [0x8FCB05A1]");
        }
    };
    public static final HLEModuleFunction sceNetIfhandleIfDown = new HLEModuleFunction("sceNetIfhandle_driver", "sceNetIfhandleIfDown") {

        @Override
        public void execute(Processor cpu, Memory mem) {
            System.out.println("Unimplement function sceNetIfhandleIfDown [0xEAD3A759]");
        }
    };
    public static final HLEModuleFunction sceNetIfhandleIfIoctl = new HLEModuleFunction("sceNetIfhandle_driver", "sceNetIfhandleIfIoctl") {

        @Override
        public void execute(Processor cpu, Memory mem) {
            System.out.println("Unimplement function sceNetIfhandleIfIoctl [0x0296C7D6]");
        }
    };
    public static final HLEModuleFunction sceNetIfhandleIfDequeue = new HLEModuleFunction("sceNetIfhandle_driver", "sceNetIfhandleIfDequeue") {

        @Override
        public void execute(Processor cpu, Memory mem) {
            System.out.println("Unimplement function sceNetIfhandleIfDequeue [0xE440A7D8]");
        }
    };
    public static final HLEModuleFunction sceNetIfhandleSignalSema = new HLEModuleFunction("sceNetIfhandle_driver", "sceNetIfhandleSignalSema") {

        @Override
        public void execute(Processor cpu, Memory mem) {
            System.out.println("Unimplement function sceNetIfhandleSignalSema [0x30602CE9]");
        }
    };
    public static final HLEModuleFunction sceNetIfhandleWaitSema = new HLEModuleFunction("sceNetIfhandle_driver", "sceNetIfhandleWaitSema") {

        @Override
        public void execute(Processor cpu, Memory mem) {
            System.out.println("Unimplement function sceNetIfhandleWaitSema [0xD5DA7B3C]");
        }
    };
    public static final HLEModuleFunction sceNetIfhandlePollSema = new HLEModuleFunction("sceNetIfhandle_driver", "sceNetIfhandlePollSema") {

        @Override
        public void execute(Processor cpu, Memory mem) {
            System.out.println("Unimplement function sceNetIfhandlePollSema [0x2162EE67]");
        }
    };
    public static final HLEModuleFunction sceNetCreateIfhandleEther = new HLEModuleFunction("sceNetIfhandle_driver", "sceNetCreateIfhandleEther") {

        @Override
        public void execute(Processor cpu, Memory mem) {
            System.out.println("Unimplement function sceNetCreateIfhandleEther [0x16042084]");
        }
    };
    public static final HLEModuleFunction sceNetDestroyIfhandleEther = new HLEModuleFunction("sceNetIfhandle_driver", "sceNetDestroyIfhandleEther") {

        @Override
        public void execute(Processor cpu, Memory mem) {
            System.out.println("Unimplement function sceNetDestroyIfhandleEther [0xC9344A59]");
        }
    };
    public static final HLEModuleFunction sceNetAttachIfhandleEther = new HLEModuleFunction("sceNetIfhandle_driver", "sceNetAttachIfhandleEther") {

        @Override
        public void execute(Processor cpu, Memory mem) {
            System.out.println("Unimplement function sceNetAttachIfhandleEther [0xAE81C0CB]");
        }
    };
    public static final HLEModuleFunction sceNetDetachIfhandleEther = new HLEModuleFunction("sceNetIfhandle_driver", "sceNetDetachIfhandleEther") {

        @Override
        public void execute(Processor cpu, Memory mem) {
            System.out.println("Unimplement function sceNetDetachIfhandleEther [0x54D1AEA1]");
        }
    };
    public static final HLEModuleFunction sceNetSendIfEvent = new HLEModuleFunction("sceNetIfhandle_driver", "sceNetSendIfEvent") {

        @Override
        public void execute(Processor cpu, Memory mem) {
            System.out.println("Unimplement function sceNetSendIfEvent [0xF94BAF52]");
        }
    };
    public static final HLEModuleFunction sceNetFlagIfEvent = new HLEModuleFunction("sceNetIfhandle_driver", "sceNetFlagIfEvent") {

        @Override
        public void execute(Processor cpu, Memory mem) {
            System.out.println("Unimplement function sceNetFlagIfEvent [0x263767F6]");
        }
    };
    public static final HLEModuleFunction sceNetIfDequeue = new HLEModuleFunction("sceNetIfhandle_driver", "sceNetIfDequeue") {

        @Override
        public void execute(Processor cpu, Memory mem) {
            System.out.println("Unimplement function sceNetIfDequeue [0xE2F4F1C9]");
        }
    };
    public static final HLEModuleFunction sceNetIfEnqueue = new HLEModuleFunction("sceNetIfhandle_driver", "sceNetIfEnqueue") {

        @Override
        public void execute(Processor cpu, Memory mem) {
            System.out.println("Unimplement function sceNetIfEnqueue [0xC28F6FF2]");
        }
    };
    public static final HLEModuleFunction sceNetIfPrepend = new HLEModuleFunction("sceNetIfhandle_driver", "sceNetIfPrepend") {

        @Override
        public void execute(Processor cpu, Memory mem) {
            System.out.println("Unimplement function sceNetIfPrepend [0x16246B99]");
        }
    };
    public static final HLEModuleFunction sceNetIfhandle_driver_C6D14282 = new HLEModuleFunction("sceNetIfhandle_driver", "sceNetIfhandle_driver_C6D14282") {

        @Override
        public void execute(Processor cpu, Memory mem) {
            System.out.println("Unimplement function sceNetIfhandle_driver_C6D14282 [0xC6D14282]");
        }
    };
    public static final HLEModuleFunction sceNetIfhandle_driver_D5AD6DEA = new HLEModuleFunction("sceNetIfhandle_driver", "sceNetIfhandle_driver_D5AD6DEA") {

        @Override
        public void execute(Processor cpu, Memory mem) {
            System.out.println("Unimplement function sceNetIfhandle_driver_D5AD6DEA [0xD5AD6DEA]");
        }
    };
    public static final HLEModuleFunction sceNetIfhandle_driver_0C391E9F = new HLEModuleFunction("sceNetIfhandle_driver", "sceNetIfhandle_driver_0C391E9F") {

        @Override
        public void execute(Processor cpu, Memory mem) {
            System.out.println("Unimplement function sceNetIfhandle_driver_0C391E9F [0x0C391E9F]");
        }
    };
    public static final HLEModuleFunction sceNetIfhandle_driver_29ED84C5 = new HLEModuleFunction("sceNetIfhandle_driver", "sceNetIfhandle_driver_29ED84C5") {

        @Override
        public void execute(Processor cpu, Memory mem) {
            System.out.println("Unimplement function sceNetIfhandle_driver_29ED84C5 [0x29ED84C5]");
        }
    };
    public static final HLEModuleFunction sceNetMallocInternal = new HLEModuleFunction("sceNetIfhandle_driver", "sceNetMallocInternal") {

        @Override
        public void execute(Processor cpu, Memory mem) {
            System.out.println("Unimplement function sceNetMallocInternal [0x15CFE3C0]");
        }
    };
    public static final HLEModuleFunction sceNetFreeInternal = new HLEModuleFunction("sceNetIfhandle_driver", "sceNetFreeInternal") {

        @Override
        public void execute(Processor cpu, Memory mem) {
            System.out.println("Unimplement function sceNetFreeInternal [0x76BAD213]");
        }
    };
    public static final HLEModuleFunction sceNetGetMallocStatInternal = new HLEModuleFunction("sceNetIfhandle_driver", "sceNetGetMallocStatInternal") {

        @Override
        public void execute(Processor cpu, Memory mem) {
            System.out.println("Unimplement function sceNetGetMallocStatInternal [0x4C2886CB]");
        }
    };
    public static final HLEModuleFunction sceNetIfhandle_driver_0FB8AE0D = new HLEModuleFunction("sceNetIfhandle_driver", "sceNetIfhandle_driver_0FB8AE0D") {

        @Override
        public void execute(Processor cpu, Memory mem) {
            System.out.println("Unimplement function sceNetIfhandle_driver_0FB8AE0D [0x0FB8AE0D]");
        }
    };
    public static final HLEModuleFunction sceNetIfhandle_driver_5FB31C72 = new HLEModuleFunction("sceNetIfhandle_driver", "sceNetIfhandle_driver_5FB31C72") {

        @Override
        public void execute(Processor cpu, Memory mem) {
            System.out.println("Unimplement function sceNetIfhandle_driver_5FB31C72 [0x5FB31C72]");
        }
    };
    public static final HLEModuleFunction sceNetIfhandle_driver_62B20015 = new HLEModuleFunction("sceNetIfhandle_driver", "sceNetIfhandle_driver_62B20015") {

        @Override
        public void execute(Processor cpu, Memory mem) {
            System.out.println("Unimplement function sceNetIfhandle_driver_62B20015 [0x62B20015]");
        }
    };
    public static final HLEModuleFunction sceNetMAdj = new HLEModuleFunction("sceNetIfhandle_driver", "sceNetMAdj") {

        @Override
        public void execute(Processor cpu, Memory mem) {
            System.out.println("Unimplement function sceNetMAdj [0xBFF3CEA5]");
        }
    };
    public static final HLEModuleFunction sceNetMCat = new HLEModuleFunction("sceNetIfhandle_driver", "sceNetMCat") {

        @Override
        public void execute(Processor cpu, Memory mem) {
            System.out.println("Unimplement function sceNetMCat [0x3E8DD3F8]");
        }
    };
    public static final HLEModuleFunction sceNetMCopyback = new HLEModuleFunction("sceNetIfhandle_driver", "sceNetMCopyback") {

        @Override
        public void execute(Processor cpu, Memory mem) {
            System.out.println("Unimplement function sceNetMCopyback [0x1560F143]");
        }
    };
    public static final HLEModuleFunction sceNetMCopydata = new HLEModuleFunction("sceNetIfhandle_driver", "sceNetMCopydata") {

        @Override
        public void execute(Processor cpu, Memory mem) {
            System.out.println("Unimplement function sceNetMCopydata [0x9A6261EC]");
        }
    };
    public static final HLEModuleFunction sceNetMCopym = new HLEModuleFunction("sceNetIfhandle_driver", "sceNetMCopym") {

        @Override
        public void execute(Processor cpu, Memory mem) {
            System.out.println("Unimplement function sceNetMCopym [0x456E3146]");
        }
    };
    public static final HLEModuleFunction sceNetIfhandle_driver_955F2924 = new HLEModuleFunction("sceNetIfhandle_driver", "sceNetIfhandle_driver_955F2924") {

        @Override
        public void execute(Processor cpu, Memory mem) {
            System.out.println("Unimplement function sceNetIfhandle_driver_955F2924 [0x955F2924]");
        }
    };
    public static final HLEModuleFunction sceNetMDup = new HLEModuleFunction("sceNetIfhandle_driver", "sceNetMDup") {

        @Override
        public void execute(Processor cpu, Memory mem) {
            System.out.println("Unimplement function sceNetMDup [0x6AB53C27]");
        }
    };
    public static final HLEModuleFunction sceNetMFree = new HLEModuleFunction("sceNetIfhandle_driver", "sceNetMFree") {

        @Override
        public void execute(Processor cpu, Memory mem) {
            System.out.println("Unimplement function sceNetMFree [0xF8825DC4]");
        }
    };
    public static final HLEModuleFunction sceNetMFreem = new HLEModuleFunction("sceNetIfhandle_driver", "sceNetMFreem") {

        @Override
        public void execute(Processor cpu, Memory mem) {
            System.out.println("Unimplement function sceNetMFreem [0xF56FAC82]");
        }
    };
    public static final HLEModuleFunction sceNetMGet = new HLEModuleFunction("sceNetIfhandle_driver", "sceNetMGet") {

        @Override
        public void execute(Processor cpu, Memory mem) {
            System.out.println("Unimplement function sceNetMGet [0xA493AA5F]");
        }
    };
    public static final HLEModuleFunction sceNetMGetclr = new HLEModuleFunction("sceNetIfhandle_driver", "sceNetMGetclr") {

        @Override
        public void execute(Processor cpu, Memory mem) {
            System.out.println("Unimplement function sceNetMGetclr [0x59F0D619]");
        }
    };
    public static final HLEModuleFunction sceNetMGethdr = new HLEModuleFunction("sceNetIfhandle_driver", "sceNetMGethdr") {

        @Override
        public void execute(Processor cpu, Memory mem) {
            System.out.println("Unimplement function sceNetMGethdr [0x4CF15C43]");
        }
    };
    public static final HLEModuleFunction sceNetMPrepend = new HLEModuleFunction("sceNetIfhandle_driver", "sceNetMPrepend") {

        @Override
        public void execute(Processor cpu, Memory mem) {
            System.out.println("Unimplement function sceNetMPrepend [0xC3325FDC]");
        }
    };
    public static final HLEModuleFunction sceNetMPulldown = new HLEModuleFunction("sceNetIfhandle_driver", "sceNetMPulldown") {

        @Override
        public void execute(Processor cpu, Memory mem) {
            System.out.println("Unimplement function sceNetMPulldown [0xE80F00A4]");
        }
    };
    public static final HLEModuleFunction sceNetMPullup = new HLEModuleFunction("sceNetIfhandle_driver", "sceNetMPullup") {

        @Override
        public void execute(Processor cpu, Memory mem) {
            System.out.println("Unimplement function sceNetMPullup [0x49EDBB18]");
        }
    };
    public static final HLEModuleFunction sceNetIfhandle_driver_0542835F = new HLEModuleFunction("sceNetIfhandle_driver", "sceNetIfhandle_driver_0542835F") {

        @Override
        public void execute(Processor cpu, Memory mem) {
            System.out.println("Unimplement function sceNetIfhandle_driver_0542835F [0x0542835F]");
        }
    };
    public static final HLEModuleFunction sceNetIfhandle_driver_773FC77C = new HLEModuleFunction("sceNetIfhandle_driver", "sceNetIfhandle_driver_773FC77C") {

        @Override
        public void execute(Processor cpu, Memory mem) {
            System.out.println("Unimplement function sceNetIfhandle_driver_773FC77C [0x773FC77C]");
        }
    };
    public static final HLEModuleFunction sceNetIfhandle_driver_9CBA24D4 = new HLEModuleFunction("sceNetIfhandle_driver", "sceNetIfhandle_driver_9CBA24D4") {

        @Override
        public void execute(Processor cpu, Memory mem) {
            System.out.println("Unimplement function sceNetIfhandle_driver_9CBA24D4 [0x9CBA24D4]");
        }
    };
    public static final HLEModuleFunction sceNetIfhandle_driver_C5623112 = new HLEModuleFunction("sceNetIfhandle_driver", "sceNetIfhandle_driver_C5623112") {

        @Override
        public void execute(Processor cpu, Memory mem) {
            System.out.println("Unimplement function sceNetIfhandle_driver_C5623112 [0xC5623112]");
        }
    };
    public static final HLEModuleFunction sceNetGetDropRate = new HLEModuleFunction("sceNetIfhandle_driver", "sceNetGetDropRate") {

        @Override
        public void execute(Processor cpu, Memory mem) {
            System.out.println("Unimplement function sceNetGetDropRate [0xC80181A2]");
        }
    };
    public static final HLEModuleFunction sceNetSetDropRate = new HLEModuleFunction("sceNetIfhandle_driver", "sceNetSetDropRate") {

        @Override
        public void execute(Processor cpu, Memory mem) {
            System.out.println("Unimplement function sceNetSetDropRate [0xFD8585E1]");
        }
    };
};
