/* This autogenerated file is part of jpcsp. */
package jpcsp.HLE.modules;

import jpcsp.HLE.pspSysMem;
import jpcsp.Memory;
import jpcsp.Processor;

public class sceNwman_driver implements HLEModule {

    @Override
    public final String getName() {
        return "sceNwman_driver";
    }

    @Override
    public void installModule(HLEModuleManager mm, int version) {

        mm.add(sceNwman_driver_9555D68D, 0x9555D68D);

    }

    @Override
    public void uninstallModule(HLEModuleManager mm, int version) {

        mm.remove(sceNwman_driver_9555D68D);

    }
    public static final HLEModuleFunction sceNwman_driver_9555D68D = new HLEModuleFunction("sceNwman_driver", "sceNwman_driver_9555D68D") {

        @Override
        public void execute(Processor cpu, Memory mem) {
            System.out.println("Unimplement function sceNwman_driver_9555D68D [0x9555D68D]");
        }
    };
};
