/* This autogenerated file is part of jpcsp. */
package jpcsp.HLE.modules;

import jpcsp.HLE.pspSysMem;
import jpcsp.Memory;
import jpcsp.Processor;

public class sceParseUri implements HLEModule {

    @Override
    public final String getName() {
        return "sceParseUri";
    }

    @Override
    public void installModule(HLEModuleManager mm, int version) {

        mm.add(sceUriEscape, 0x49E950EC);

        mm.add(sceUriUnescape, 0x062BB07E);

        mm.add(sceUriParse, 0x568518C9);

        mm.add(sceUriBuild, 0x7EE318AF);

    }

    @Override
    public void uninstallModule(HLEModuleManager mm, int version) {

        mm.remove(sceUriEscape);

        mm.remove(sceUriUnescape);

        mm.remove(sceUriParse);

        mm.remove(sceUriBuild);

    }
    public static final HLEModuleFunction sceUriEscape = new HLEModuleFunction("sceParseUri", "sceUriEscape") {

        @Override
        public void execute(Processor cpu, Memory mem) {
            System.out.println("Unimplement function sceUriEscape [0x49E950EC]");
        }
    };
    public static final HLEModuleFunction sceUriUnescape = new HLEModuleFunction("sceParseUri", "sceUriUnescape") {

        @Override
        public void execute(Processor cpu, Memory mem) {
            System.out.println("Unimplement function sceUriUnescape [0x062BB07E]");
        }
    };
    public static final HLEModuleFunction sceUriParse = new HLEModuleFunction("sceParseUri", "sceUriParse") {

        @Override
        public void execute(Processor cpu, Memory mem) {
            System.out.println("Unimplement function sceUriParse [0x568518C9]");
        }
    };
    public static final HLEModuleFunction sceUriBuild = new HLEModuleFunction("sceParseUri", "sceUriBuild") {

        @Override
        public void execute(Processor cpu, Memory mem) {
            System.out.println("Unimplement function sceUriBuild [0x7EE318AF]");
        }
    };
};
