/* This autogenerated file is part of jpcsp. */
package jpcsp.HLE.modules;

import jpcsp.HLE.pspSysMem;
import jpcsp.Memory;
import jpcsp.Processor;

public class vsh implements HLEModule {

    @Override
    public final String getName() {
        return "vsh";
    }

    @Override
    public void installModule(HLEModuleManager mm, int version) {

        mm.add(vsh_0B8DE38E, 0x0B8DE38E);

        mm.add(vsh_0E20CEEC, 0x0E20CEEC);

        mm.add(vsh_61FE226A, 0x61FE226A);

        mm.add(vsh_0F2F6718, 0x0F2F6718);

        mm.add(vsh_5E43E468, 0x5E43E468);

        mm.add(vsh_D0A3A365, 0xD0A3A365);

        mm.add(vsh_7ADF6A69, 0x7ADF6A69);

        mm.add(vsh_1A62E6EA, 0x1A62E6EA);

        mm.add(vsh_5452A47B, 0x5452A47B);

        mm.add(vsh_81BBD0D1, 0x81BBD0D1);

        mm.add(vsh_6286E89D, 0x6286E89D);

        mm.add(vsh_34DA1B67, 0x34DA1B67);

        mm.add(vsh_F1A72B42, 0xF1A72B42);

        mm.add(vsh_7DA81064, 0x7DA81064);

        mm.add(vsh_FDEE4109, 0xFDEE4109);

        mm.add(vsh_A3C7DF11, 0xA3C7DF11);

        mm.add(vsh_B55C095C, 0xB55C095C);

        mm.add(vsh_80FB409B, 0x80FB409B);

        mm.add(vsh_595F8E64, 0x595F8E64);

        mm.add(vsh_8F76CA2A, 0x8F76CA2A);

        mm.add(vsh_4A619A1D, 0x4A619A1D);

        mm.add(vsh_3E00F3B4, 0x3E00F3B4);

        mm.add(vsh_2695A5B8, 0x2695A5B8);

        mm.add(vvvGetVersion, 0x182745AF);

        mm.add(vsh_58925420, 0x58925420);

        mm.add(vsh_78A67F41, 0x78A67F41);

        mm.add(vsh_AA8B9556, 0xAA8B9556);

        mm.add(vsh_EF3DAF7D, 0xEF3DAF7D);

        mm.add(vsh_71C15234, 0x71C15234);

        mm.add(vsh_B55DCA45, 0xB55DCA45);

        mm.add(vsh_741C9BE1, 0x741C9BE1);

        mm.add(vsh_2B8B7775, 0x2B8B7775);

        mm.add(vsh_163B90CB, 0x163B90CB);

        mm.add(vsh_7B9AA4D4, 0x7B9AA4D4);

        mm.add(vsh_A0CBE1FE, 0xA0CBE1FE);

    }

    @Override
    public void uninstallModule(HLEModuleManager mm, int version) {

        mm.remove(vsh_0B8DE38E);

        mm.remove(vsh_0E20CEEC);

        mm.remove(vsh_61FE226A);

        mm.remove(vsh_0F2F6718);

        mm.remove(vsh_5E43E468);

        mm.remove(vsh_D0A3A365);

        mm.remove(vsh_7ADF6A69);

        mm.remove(vsh_1A62E6EA);

        mm.remove(vsh_5452A47B);

        mm.remove(vsh_81BBD0D1);

        mm.remove(vsh_6286E89D);

        mm.remove(vsh_34DA1B67);

        mm.remove(vsh_F1A72B42);

        mm.remove(vsh_7DA81064);

        mm.remove(vsh_FDEE4109);

        mm.remove(vsh_A3C7DF11);

        mm.remove(vsh_B55C095C);

        mm.remove(vsh_80FB409B);

        mm.remove(vsh_595F8E64);

        mm.remove(vsh_8F76CA2A);

        mm.remove(vsh_4A619A1D);

        mm.remove(vsh_3E00F3B4);

        mm.remove(vsh_2695A5B8);

        mm.remove(vvvGetVersion);

        mm.remove(vsh_58925420);

        mm.remove(vsh_78A67F41);

        mm.remove(vsh_AA8B9556);

        mm.remove(vsh_EF3DAF7D);

        mm.remove(vsh_71C15234);

        mm.remove(vsh_B55DCA45);

        mm.remove(vsh_741C9BE1);

        mm.remove(vsh_2B8B7775);

        mm.remove(vsh_163B90CB);

        mm.remove(vsh_7B9AA4D4);

        mm.remove(vsh_A0CBE1FE);

    }
    public static final HLEModuleFunction vsh_0B8DE38E = new HLEModuleFunction("vsh", "vsh_0B8DE38E") {

        @Override
        public void execute(Processor cpu, Memory mem) {
            System.out.println("Unimplement function vsh_0B8DE38E [0x0B8DE38E]");
        }
    };
    public static final HLEModuleFunction vsh_0E20CEEC = new HLEModuleFunction("vsh", "vsh_0E20CEEC") {

        @Override
        public void execute(Processor cpu, Memory mem) {
            System.out.println("Unimplement function vsh_0E20CEEC [0x0E20CEEC]");
        }
    };
    public static final HLEModuleFunction vsh_61FE226A = new HLEModuleFunction("vsh", "vsh_61FE226A") {

        @Override
        public void execute(Processor cpu, Memory mem) {
            System.out.println("Unimplement function vsh_61FE226A [0x61FE226A]");
        }
    };
    public static final HLEModuleFunction vsh_0F2F6718 = new HLEModuleFunction("vsh", "vsh_0F2F6718") {

        @Override
        public void execute(Processor cpu, Memory mem) {
            System.out.println("Unimplement function vsh_0F2F6718 [0x0F2F6718]");
        }
    };
    public static final HLEModuleFunction vsh_5E43E468 = new HLEModuleFunction("vsh", "vsh_5E43E468") {

        @Override
        public void execute(Processor cpu, Memory mem) {
            System.out.println("Unimplement function vsh_5E43E468 [0x5E43E468]");
        }
    };
    public static final HLEModuleFunction vsh_D0A3A365 = new HLEModuleFunction("vsh", "vsh_D0A3A365") {

        @Override
        public void execute(Processor cpu, Memory mem) {
            System.out.println("Unimplement function vsh_D0A3A365 [0xD0A3A365]");
        }
    };
    public static final HLEModuleFunction vsh_7ADF6A69 = new HLEModuleFunction("vsh", "vsh_7ADF6A69") {

        @Override
        public void execute(Processor cpu, Memory mem) {
            System.out.println("Unimplement function vsh_7ADF6A69 [0x7ADF6A69]");
        }
    };
    public static final HLEModuleFunction vsh_1A62E6EA = new HLEModuleFunction("vsh", "vsh_1A62E6EA") {

        @Override
        public void execute(Processor cpu, Memory mem) {
            System.out.println("Unimplement function vsh_1A62E6EA [0x1A62E6EA]");
        }
    };
    public static final HLEModuleFunction vsh_5452A47B = new HLEModuleFunction("vsh", "vsh_5452A47B") {

        @Override
        public void execute(Processor cpu, Memory mem) {
            System.out.println("Unimplement function vsh_5452A47B [0x5452A47B]");
        }
    };
    public static final HLEModuleFunction vsh_81BBD0D1 = new HLEModuleFunction("vsh", "vsh_81BBD0D1") {

        @Override
        public void execute(Processor cpu, Memory mem) {
            System.out.println("Unimplement function vsh_81BBD0D1 [0x81BBD0D1]");
        }
    };
    public static final HLEModuleFunction vsh_6286E89D = new HLEModuleFunction("vsh", "vsh_6286E89D") {

        @Override
        public void execute(Processor cpu, Memory mem) {
            System.out.println("Unimplement function vsh_6286E89D [0x6286E89D]");
        }
    };
    public static final HLEModuleFunction vsh_34DA1B67 = new HLEModuleFunction("vsh", "vsh_34DA1B67") {

        @Override
        public void execute(Processor cpu, Memory mem) {
            System.out.println("Unimplement function vsh_34DA1B67 [0x34DA1B67]");
        }
    };
    public static final HLEModuleFunction vsh_F1A72B42 = new HLEModuleFunction("vsh", "vsh_F1A72B42") {

        @Override
        public void execute(Processor cpu, Memory mem) {
            System.out.println("Unimplement function vsh_F1A72B42 [0xF1A72B42]");
        }
    };
    public static final HLEModuleFunction vsh_7DA81064 = new HLEModuleFunction("vsh", "vsh_7DA81064") {

        @Override
        public void execute(Processor cpu, Memory mem) {
            System.out.println("Unimplement function vsh_7DA81064 [0x7DA81064]");
        }
    };
    public static final HLEModuleFunction vsh_FDEE4109 = new HLEModuleFunction("vsh", "vsh_FDEE4109") {

        @Override
        public void execute(Processor cpu, Memory mem) {
            System.out.println("Unimplement function vsh_FDEE4109 [0xFDEE4109]");
        }
    };
    public static final HLEModuleFunction vsh_A3C7DF11 = new HLEModuleFunction("vsh", "vsh_A3C7DF11") {

        @Override
        public void execute(Processor cpu, Memory mem) {
            System.out.println("Unimplement function vsh_A3C7DF11 [0xA3C7DF11]");
        }
    };
    public static final HLEModuleFunction vsh_B55C095C = new HLEModuleFunction("vsh", "vsh_B55C095C") {

        @Override
        public void execute(Processor cpu, Memory mem) {
            System.out.println("Unimplement function vsh_B55C095C [0xB55C095C]");
        }
    };
    public static final HLEModuleFunction vsh_80FB409B = new HLEModuleFunction("vsh", "vsh_80FB409B") {

        @Override
        public void execute(Processor cpu, Memory mem) {
            System.out.println("Unimplement function vsh_80FB409B [0x80FB409B]");
        }
    };
    public static final HLEModuleFunction vsh_595F8E64 = new HLEModuleFunction("vsh", "vsh_595F8E64") {

        @Override
        public void execute(Processor cpu, Memory mem) {
            System.out.println("Unimplement function vsh_595F8E64 [0x595F8E64]");
        }
    };
    public static final HLEModuleFunction vsh_8F76CA2A = new HLEModuleFunction("vsh", "vsh_8F76CA2A") {

        @Override
        public void execute(Processor cpu, Memory mem) {
            System.out.println("Unimplement function vsh_8F76CA2A [0x8F76CA2A]");
        }
    };
    public static final HLEModuleFunction vsh_4A619A1D = new HLEModuleFunction("vsh", "vsh_4A619A1D") {

        @Override
        public void execute(Processor cpu, Memory mem) {
            System.out.println("Unimplement function vsh_4A619A1D [0x4A619A1D]");
        }
    };
    public static final HLEModuleFunction vsh_3E00F3B4 = new HLEModuleFunction("vsh", "vsh_3E00F3B4") {

        @Override
        public void execute(Processor cpu, Memory mem) {
            System.out.println("Unimplement function vsh_3E00F3B4 [0x3E00F3B4]");
        }
    };
    public static final HLEModuleFunction vsh_2695A5B8 = new HLEModuleFunction("vsh", "vsh_2695A5B8") {

        @Override
        public void execute(Processor cpu, Memory mem) {
            System.out.println("Unimplement function vsh_2695A5B8 [0x2695A5B8]");
        }
    };
    public static final HLEModuleFunction vvvGetVersion = new HLEModuleFunction("vsh", "vvvGetVersion") {

        @Override
        public void execute(Processor cpu, Memory mem) {
            System.out.println("Unimplement function vvvGetVersion [0x182745AF]");
        }
    };
    public static final HLEModuleFunction vsh_58925420 = new HLEModuleFunction("vsh", "vsh_58925420") {

        @Override
        public void execute(Processor cpu, Memory mem) {
            System.out.println("Unimplement function vsh_58925420 [0x58925420]");
        }
    };
    public static final HLEModuleFunction vsh_78A67F41 = new HLEModuleFunction("vsh", "vsh_78A67F41") {

        @Override
        public void execute(Processor cpu, Memory mem) {
            System.out.println("Unimplement function vsh_78A67F41 [0x78A67F41]");
        }
    };
    public static final HLEModuleFunction vsh_AA8B9556 = new HLEModuleFunction("vsh", "vsh_AA8B9556") {

        @Override
        public void execute(Processor cpu, Memory mem) {
            System.out.println("Unimplement function vsh_AA8B9556 [0xAA8B9556]");
        }
    };
    public static final HLEModuleFunction vsh_EF3DAF7D = new HLEModuleFunction("vsh", "vsh_EF3DAF7D") {

        @Override
        public void execute(Processor cpu, Memory mem) {
            System.out.println("Unimplement function vsh_EF3DAF7D [0xEF3DAF7D]");
        }
    };
    public static final HLEModuleFunction vsh_71C15234 = new HLEModuleFunction("vsh", "vsh_71C15234") {

        @Override
        public void execute(Processor cpu, Memory mem) {
            System.out.println("Unimplement function vsh_71C15234 [0x71C15234]");
        }
    };
    public static final HLEModuleFunction vsh_B55DCA45 = new HLEModuleFunction("vsh", "vsh_B55DCA45") {

        @Override
        public void execute(Processor cpu, Memory mem) {
            System.out.println("Unimplement function vsh_B55DCA45 [0xB55DCA45]");
        }
    };
    public static final HLEModuleFunction vsh_741C9BE1 = new HLEModuleFunction("vsh", "vsh_741C9BE1") {

        @Override
        public void execute(Processor cpu, Memory mem) {
            System.out.println("Unimplement function vsh_741C9BE1 [0x741C9BE1]");
        }
    };
    public static final HLEModuleFunction vsh_2B8B7775 = new HLEModuleFunction("vsh", "vsh_2B8B7775") {

        @Override
        public void execute(Processor cpu, Memory mem) {
            System.out.println("Unimplement function vsh_2B8B7775 [0x2B8B7775]");
        }
    };
    public static final HLEModuleFunction vsh_163B90CB = new HLEModuleFunction("vsh", "vsh_163B90CB") {

        @Override
        public void execute(Processor cpu, Memory mem) {
            System.out.println("Unimplement function vsh_163B90CB [0x163B90CB]");
        }
    };
    public static final HLEModuleFunction vsh_7B9AA4D4 = new HLEModuleFunction("vsh", "vsh_7B9AA4D4") {

        @Override
        public void execute(Processor cpu, Memory mem) {
            System.out.println("Unimplement function vsh_7B9AA4D4 [0x7B9AA4D4]");
        }
    };
    public static final HLEModuleFunction vsh_A0CBE1FE = new HLEModuleFunction("vsh", "vsh_A0CBE1FE") {

        @Override
        public void execute(Processor cpu, Memory mem) {
            System.out.println("Unimplement function vsh_A0CBE1FE [0xA0CBE1FE]");
        }
    };
};
