/* This autogenerated file is part of jpcsp. */
package jpcsp.HLE.modules;

import jpcsp.HLE.pspSysMem;
import jpcsp.Memory;
import jpcsp.Processor;

public class sceMesgLed_driver implements HLEModule {

    @Override
    public final String getName() {
        return "sceMesgLed_driver";
    }

    @Override
    public void installModule(HLEModuleManager mm, int version) {

        mm.add(sceMesgLed_driver_84A04017, 0x84A04017);

        mm.add(sceMesgLed_driver_A86D5005, 0xA86D5005);

        mm.add(sceMesgLed_driver_A4547DF1, 0xA4547DF1);

        mm.add(sceMesgLed_driver_94EB1072, 0x94EB1072);

        mm.add(sceMesgLed_driver_198FD3BE, 0x198FD3BE);

        mm.add(sceMesgLed_driver_FBC694C7, 0xFBC694C7);

        mm.add(sceMesgLed_driver_07E152BE, 0x07E152BE);

        mm.add(sceMesgLed_driver_9906F33A, 0x9906F33A);

        mm.add(sceMesgLed_driver_46AC0E78, 0x46AC0E78);

        mm.add(sceMesgLed_driver_55C8785E, 0x55C8785E);

        mm.add(sceMesgLed_driver_67A5ECDF, 0x67A5ECDF);

        mm.add(sceMesgLed_driver_85B9D9F3, 0x85B9D9F3);

        mm.add(sceMesgLed_driver_951F4A5B, 0x951F4A5B);

        mm.add(sceMesgLed_driver_58999D8E, 0x58999D8E);

        mm.add(sceMesgLed_driver_9FC926A0, 0x9FC926A0);

        mm.add(sceMesgLed_driver_7A922276, 0x7A922276);

    }

    @Override
    public void uninstallModule(HLEModuleManager mm, int version) {

        mm.remove(sceMesgLed_driver_84A04017);

        mm.remove(sceMesgLed_driver_A86D5005);

        mm.remove(sceMesgLed_driver_A4547DF1);

        mm.remove(sceMesgLed_driver_94EB1072);

        mm.remove(sceMesgLed_driver_198FD3BE);

        mm.remove(sceMesgLed_driver_FBC694C7);

        mm.remove(sceMesgLed_driver_07E152BE);

        mm.remove(sceMesgLed_driver_9906F33A);

        mm.remove(sceMesgLed_driver_46AC0E78);

        mm.remove(sceMesgLed_driver_55C8785E);

        mm.remove(sceMesgLed_driver_67A5ECDF);

        mm.remove(sceMesgLed_driver_85B9D9F3);

        mm.remove(sceMesgLed_driver_951F4A5B);

        mm.remove(sceMesgLed_driver_58999D8E);

        mm.remove(sceMesgLed_driver_9FC926A0);

        mm.remove(sceMesgLed_driver_7A922276);

    }
    public static final HLEModuleFunction sceMesgLed_driver_84A04017 = new HLEModuleFunction("sceMesgLed_driver", "sceMesgLed_driver_84A04017") {

        @Override
        public void execute(Processor cpu, Memory mem) {
            System.out.println("Unimplement function sceMesgLed_driver_84A04017 [0x84A04017]");
        }
    };
    public static final HLEModuleFunction sceMesgLed_driver_A86D5005 = new HLEModuleFunction("sceMesgLed_driver", "sceMesgLed_driver_A86D5005") {

        @Override
        public void execute(Processor cpu, Memory mem) {
            System.out.println("Unimplement function sceMesgLed_driver_A86D5005 [0xA86D5005]");
        }
    };
    public static final HLEModuleFunction sceMesgLed_driver_A4547DF1 = new HLEModuleFunction("sceMesgLed_driver", "sceMesgLed_driver_A4547DF1") {

        @Override
        public void execute(Processor cpu, Memory mem) {
            System.out.println("Unimplement function sceMesgLed_driver_A4547DF1 [0xA4547DF1]");
        }
    };
    public static final HLEModuleFunction sceMesgLed_driver_94EB1072 = new HLEModuleFunction("sceMesgLed_driver", "sceMesgLed_driver_94EB1072") {

        @Override
        public void execute(Processor cpu, Memory mem) {
            System.out.println("Unimplement function sceMesgLed_driver_94EB1072 [0x94EB1072]");
        }
    };
    public static final HLEModuleFunction sceMesgLed_driver_198FD3BE = new HLEModuleFunction("sceMesgLed_driver", "sceMesgLed_driver_198FD3BE") {

        @Override
        public void execute(Processor cpu, Memory mem) {
            System.out.println("Unimplement function sceMesgLed_driver_198FD3BE [0x198FD3BE]");
        }
    };
    public static final HLEModuleFunction sceMesgLed_driver_FBC694C7 = new HLEModuleFunction("sceMesgLed_driver", "sceMesgLed_driver_FBC694C7") {

        @Override
        public void execute(Processor cpu, Memory mem) {
            System.out.println("Unimplement function sceMesgLed_driver_FBC694C7 [0xFBC694C7]");
        }
    };
    public static final HLEModuleFunction sceMesgLed_driver_07E152BE = new HLEModuleFunction("sceMesgLed_driver", "sceMesgLed_driver_07E152BE") {

        @Override
        public void execute(Processor cpu, Memory mem) {
            System.out.println("Unimplement function sceMesgLed_driver_07E152BE [0x07E152BE]");
        }
    };
    public static final HLEModuleFunction sceMesgLed_driver_9906F33A = new HLEModuleFunction("sceMesgLed_driver", "sceMesgLed_driver_9906F33A") {

        @Override
        public void execute(Processor cpu, Memory mem) {
            System.out.println("Unimplement function sceMesgLed_driver_9906F33A [0x9906F33A]");
        }
    };
    public static final HLEModuleFunction sceMesgLed_driver_46AC0E78 = new HLEModuleFunction("sceMesgLed_driver", "sceMesgLed_driver_46AC0E78") {

        @Override
        public void execute(Processor cpu, Memory mem) {
            System.out.println("Unimplement function sceMesgLed_driver_46AC0E78 [0x46AC0E78]");
        }
    };
    public static final HLEModuleFunction sceMesgLed_driver_55C8785E = new HLEModuleFunction("sceMesgLed_driver", "sceMesgLed_driver_55C8785E") {

        @Override
        public void execute(Processor cpu, Memory mem) {
            System.out.println("Unimplement function sceMesgLed_driver_55C8785E [0x55C8785E]");
        }
    };
    public static final HLEModuleFunction sceMesgLed_driver_67A5ECDF = new HLEModuleFunction("sceMesgLed_driver", "sceMesgLed_driver_67A5ECDF") {

        @Override
        public void execute(Processor cpu, Memory mem) {
            System.out.println("Unimplement function sceMesgLed_driver_67A5ECDF [0x67A5ECDF]");
        }
    };
    public static final HLEModuleFunction sceMesgLed_driver_85B9D9F3 = new HLEModuleFunction("sceMesgLed_driver", "sceMesgLed_driver_85B9D9F3") {

        @Override
        public void execute(Processor cpu, Memory mem) {
            System.out.println("Unimplement function sceMesgLed_driver_85B9D9F3 [0x85B9D9F3]");
        }
    };
    public static final HLEModuleFunction sceMesgLed_driver_951F4A5B = new HLEModuleFunction("sceMesgLed_driver", "sceMesgLed_driver_951F4A5B") {

        @Override
        public void execute(Processor cpu, Memory mem) {
            System.out.println("Unimplement function sceMesgLed_driver_951F4A5B [0x951F4A5B]");
        }
    };
    public static final HLEModuleFunction sceMesgLed_driver_58999D8E = new HLEModuleFunction("sceMesgLed_driver", "sceMesgLed_driver_58999D8E") {

        @Override
        public void execute(Processor cpu, Memory mem) {
            System.out.println("Unimplement function sceMesgLed_driver_58999D8E [0x58999D8E]");
        }
    };
    public static final HLEModuleFunction sceMesgLed_driver_9FC926A0 = new HLEModuleFunction("sceMesgLed_driver", "sceMesgLed_driver_9FC926A0") {

        @Override
        public void execute(Processor cpu, Memory mem) {
            System.out.println("Unimplement function sceMesgLed_driver_9FC926A0 [0x9FC926A0]");
        }
    };
    public static final HLEModuleFunction sceMesgLed_driver_7A922276 = new HLEModuleFunction("sceMesgLed_driver", "sceMesgLed_driver_7A922276") {

        @Override
        public void execute(Processor cpu, Memory mem) {
            System.out.println("Unimplement function sceMesgLed_driver_7A922276 [0x7A922276]");
        }
    };
};
