/* This autogenerated file is part of jpcsp. */
package jpcsp.HLE.modules;

import jpcsp.HLE.pspSysMem;
import jpcsp.Memory;
import jpcsp.Processor;

public class sceNetApctl_internal_user implements HLEModule {

    @Override
    public final String getName() {
        return "sceNetApctl_internal_user";
    }

    @Override
    public void installModule(HLEModuleManager mm, int version) {

        mm.add(sceNetApctlScanUser, 0xE9B2E5E6);

        mm.add(sceNetApctlGetBSSDescIDListUser, 0x6BDDCB8C);

        mm.add(sceNetApctlGetBSSDescEntryUser, 0x04776994);

    }

    @Override
    public void uninstallModule(HLEModuleManager mm, int version) {

        mm.remove(sceNetApctlScanUser);

        mm.remove(sceNetApctlGetBSSDescIDListUser);

        mm.remove(sceNetApctlGetBSSDescEntryUser);

    }
    public static final HLEModuleFunction sceNetApctlScanUser = new HLEModuleFunction("sceNetApctl_internal_user", "sceNetApctlScanUser") {

        @Override
        public void execute(Processor cpu, Memory mem) {
            System.out.println("Unimplement function sceNetApctlScanUser [0xE9B2E5E6]");
        }
    };
    public static final HLEModuleFunction sceNetApctlGetBSSDescIDListUser = new HLEModuleFunction("sceNetApctl_internal_user", "sceNetApctlGetBSSDescIDListUser") {

        @Override
        public void execute(Processor cpu, Memory mem) {
            System.out.println("Unimplement function sceNetApctlGetBSSDescIDListUser [0x6BDDCB8C]");
        }
    };
    public static final HLEModuleFunction sceNetApctlGetBSSDescEntryUser = new HLEModuleFunction("sceNetApctl_internal_user", "sceNetApctlGetBSSDescEntryUser") {

        @Override
        public void execute(Processor cpu, Memory mem) {
            System.out.println("Unimplement function sceNetApctlGetBSSDescEntryUser [0x04776994]");
        }
    };
};
