/* This autogenerated file is part of jpcsp. */
package jpcsp.HLE.modules;

import jpcsp.HLE.pspSysMem;
import jpcsp.Memory;
import jpcsp.Processor;

public class sceWlanDrv_driver implements HLEModule {

    @Override
    public final String getName() {
        return "sceWlanDrv_driver";
    }

    @Override
    public void installModule(HLEModuleManager mm, int version) {

        mm.add(sceWlanDevInit, 0x6D89822C);

        mm.add(sceWlanDevEnd, 0xEC9232F0);

        mm.add(sceWlanDevAttach, 0x482CAE9A);

        mm.add(sceWlanDevDetach, 0xC9A8CAB7);

        mm.add(sceWlanDevIsPowerOn, 0x93440B11);

        mm.add(sceWlanDevGetMacAddr, 0x19E51F54);

        mm.add(sceWlanDevIsGameMode, 0x5E7C8D94);

        mm.add(sceWlanGPPrevEstablishActive, 0x5ED4049A);

        mm.add(sceWlanGPSend, 0xB4D7CB74);

        mm.add(sceWlanGPRecv, 0xA447103A);

        mm.add(sceWlanGPRegisterCallback, 0x9658C9F7);

        mm.add(sceWlanGPUnRegisterCallback, 0x4C7F62E0);

        mm.add(sceWlanDrv_driver_81579D36, 0x81579D36);

        mm.add(sceWlanDrv_driver_5BAA1FE5, 0x5BAA1FE5);

        mm.add(sceWlanDrv_driver_4C14BACA, 0x4C14BACA);

        mm.add(sceWlanDrv_driver_2D0FAE4E, 0x2D0FAE4E);

        mm.add(sceWlanDrv_driver_56F467CA, 0x56F467CA);

        mm.add(sceWlanSetWakeUp, 0xFE8A0B46);

        mm.add(sceWlanDrv_driver_40B0AA4A, 0x40B0AA4A);

        mm.add(sceWlanDevSetGPIO, 0x7FF54BD2);

        mm.add(sceWlanDevGetStateGPIO, 0x05FE320C);

        mm.add(sceWlanDrv_driver_8D5F551B, 0x8D5F551B);

    }

    @Override
    public void uninstallModule(HLEModuleManager mm, int version) {

        mm.remove(sceWlanDevInit);

        mm.remove(sceWlanDevEnd);

        mm.remove(sceWlanDevAttach);

        mm.remove(sceWlanDevDetach);

        mm.remove(sceWlanDevIsPowerOn);

        mm.remove(sceWlanDevGetMacAddr);

        mm.remove(sceWlanDevIsGameMode);

        mm.remove(sceWlanGPPrevEstablishActive);

        mm.remove(sceWlanGPSend);

        mm.remove(sceWlanGPRecv);

        mm.remove(sceWlanGPRegisterCallback);

        mm.remove(sceWlanGPUnRegisterCallback);

        mm.remove(sceWlanDrv_driver_81579D36);

        mm.remove(sceWlanDrv_driver_5BAA1FE5);

        mm.remove(sceWlanDrv_driver_4C14BACA);

        mm.remove(sceWlanDrv_driver_2D0FAE4E);

        mm.remove(sceWlanDrv_driver_56F467CA);

        mm.remove(sceWlanSetWakeUp);

        mm.remove(sceWlanDrv_driver_40B0AA4A);

        mm.remove(sceWlanDevSetGPIO);

        mm.remove(sceWlanDevGetStateGPIO);

        mm.remove(sceWlanDrv_driver_8D5F551B);

    }
    public static final HLEModuleFunction sceWlanDevInit = new HLEModuleFunction("sceWlanDrv_driver", "sceWlanDevInit") {

        @Override
        public void execute(Processor cpu, Memory mem) {
            System.out.println("Unimplement function sceWlanDevInit [0x6D89822C]");
        }
    };
    public static final HLEModuleFunction sceWlanDevEnd = new HLEModuleFunction("sceWlanDrv_driver", "sceWlanDevEnd") {

        @Override
        public void execute(Processor cpu, Memory mem) {
            System.out.println("Unimplement function sceWlanDevEnd [0xEC9232F0]");
        }
    };
    public static final HLEModuleFunction sceWlanDevAttach = new HLEModuleFunction("sceWlanDrv_driver", "sceWlanDevAttach") {

        @Override
        public void execute(Processor cpu, Memory mem) {
            System.out.println("Unimplement function sceWlanDevAttach [0x482CAE9A]");
        }
    };
    public static final HLEModuleFunction sceWlanDevDetach = new HLEModuleFunction("sceWlanDrv_driver", "sceWlanDevDetach") {

        @Override
        public void execute(Processor cpu, Memory mem) {
            System.out.println("Unimplement function sceWlanDevDetach [0xC9A8CAB7]");
        }
    };
    public static final HLEModuleFunction sceWlanDevIsPowerOn = new HLEModuleFunction("sceWlanDrv_driver", "sceWlanDevIsPowerOn") {

        @Override
        public void execute(Processor cpu, Memory mem) {
            System.out.println("Unimplement function sceWlanDevIsPowerOn [0x93440B11]");
        }
    };
    public static final HLEModuleFunction sceWlanDevGetMacAddr = new HLEModuleFunction("sceWlanDrv_driver", "sceWlanDevGetMacAddr") {

        @Override
        public void execute(Processor cpu, Memory mem) {
            System.out.println("Unimplement function sceWlanDevGetMacAddr [0x19E51F54]");
        }
    };
    public static final HLEModuleFunction sceWlanDevIsGameMode = new HLEModuleFunction("sceWlanDrv_driver", "sceWlanDevIsGameMode") {

        @Override
        public void execute(Processor cpu, Memory mem) {
            System.out.println("Unimplement function sceWlanDevIsGameMode [0x5E7C8D94]");
        }
    };
    public static final HLEModuleFunction sceWlanGPPrevEstablishActive = new HLEModuleFunction("sceWlanDrv_driver", "sceWlanGPPrevEstablishActive") {

        @Override
        public void execute(Processor cpu, Memory mem) {
            System.out.println("Unimplement function sceWlanGPPrevEstablishActive [0x5ED4049A]");
        }
    };
    public static final HLEModuleFunction sceWlanGPSend = new HLEModuleFunction("sceWlanDrv_driver", "sceWlanGPSend") {

        @Override
        public void execute(Processor cpu, Memory mem) {
            System.out.println("Unimplement function sceWlanGPSend [0xB4D7CB74]");
        }
    };
    public static final HLEModuleFunction sceWlanGPRecv = new HLEModuleFunction("sceWlanDrv_driver", "sceWlanGPRecv") {

        @Override
        public void execute(Processor cpu, Memory mem) {
            System.out.println("Unimplement function sceWlanGPRecv [0xA447103A]");
        }
    };
    public static final HLEModuleFunction sceWlanGPRegisterCallback = new HLEModuleFunction("sceWlanDrv_driver", "sceWlanGPRegisterCallback") {

        @Override
        public void execute(Processor cpu, Memory mem) {
            System.out.println("Unimplement function sceWlanGPRegisterCallback [0x9658C9F7]");
        }
    };
    public static final HLEModuleFunction sceWlanGPUnRegisterCallback = new HLEModuleFunction("sceWlanDrv_driver", "sceWlanGPUnRegisterCallback") {

        @Override
        public void execute(Processor cpu, Memory mem) {
            System.out.println("Unimplement function sceWlanGPUnRegisterCallback [0x4C7F62E0]");
        }
    };
    public static final HLEModuleFunction sceWlanDrv_driver_81579D36 = new HLEModuleFunction("sceWlanDrv_driver", "sceWlanDrv_driver_81579D36") {

        @Override
        public void execute(Processor cpu, Memory mem) {
            System.out.println("Unimplement function sceWlanDrv_driver_81579D36 [0x81579D36]");
        }
    };
    public static final HLEModuleFunction sceWlanDrv_driver_5BAA1FE5 = new HLEModuleFunction("sceWlanDrv_driver", "sceWlanDrv_driver_5BAA1FE5") {

        @Override
        public void execute(Processor cpu, Memory mem) {
            System.out.println("Unimplement function sceWlanDrv_driver_5BAA1FE5 [0x5BAA1FE5]");
        }
    };
    public static final HLEModuleFunction sceWlanDrv_driver_4C14BACA = new HLEModuleFunction("sceWlanDrv_driver", "sceWlanDrv_driver_4C14BACA") {

        @Override
        public void execute(Processor cpu, Memory mem) {
            System.out.println("Unimplement function sceWlanDrv_driver_4C14BACA [0x4C14BACA]");
        }
    };
    public static final HLEModuleFunction sceWlanDrv_driver_2D0FAE4E = new HLEModuleFunction("sceWlanDrv_driver", "sceWlanDrv_driver_2D0FAE4E") {

        @Override
        public void execute(Processor cpu, Memory mem) {
            System.out.println("Unimplement function sceWlanDrv_driver_2D0FAE4E [0x2D0FAE4E]");
        }
    };
    public static final HLEModuleFunction sceWlanDrv_driver_56F467CA = new HLEModuleFunction("sceWlanDrv_driver", "sceWlanDrv_driver_56F467CA") {

        @Override
        public void execute(Processor cpu, Memory mem) {
            System.out.println("Unimplement function sceWlanDrv_driver_56F467CA [0x56F467CA]");
        }
    };
    public static final HLEModuleFunction sceWlanSetWakeUp = new HLEModuleFunction("sceWlanDrv_driver", "sceWlanSetWakeUp") {

        @Override
        public void execute(Processor cpu, Memory mem) {
            System.out.println("Unimplement function sceWlanSetWakeUp [0xFE8A0B46]");
        }
    };
    public static final HLEModuleFunction sceWlanDrv_driver_40B0AA4A = new HLEModuleFunction("sceWlanDrv_driver", "sceWlanDrv_driver_40B0AA4A") {

        @Override
        public void execute(Processor cpu, Memory mem) {
            System.out.println("Unimplement function sceWlanDrv_driver_40B0AA4A [0x40B0AA4A]");
        }
    };
    public static final HLEModuleFunction sceWlanDevSetGPIO = new HLEModuleFunction("sceWlanDrv_driver", "sceWlanDevSetGPIO") {

        @Override
        public void execute(Processor cpu, Memory mem) {
            System.out.println("Unimplement function sceWlanDevSetGPIO [0x7FF54BD2]");
        }
    };
    public static final HLEModuleFunction sceWlanDevGetStateGPIO = new HLEModuleFunction("sceWlanDrv_driver", "sceWlanDevGetStateGPIO") {

        @Override
        public void execute(Processor cpu, Memory mem) {
            System.out.println("Unimplement function sceWlanDevGetStateGPIO [0x05FE320C]");
        }
    };
    public static final HLEModuleFunction sceWlanDrv_driver_8D5F551B = new HLEModuleFunction("sceWlanDrv_driver", "sceWlanDrv_driver_8D5F551B") {

        @Override
        public void execute(Processor cpu, Memory mem) {
            System.out.println("Unimplement function sceWlanDrv_driver_8D5F551B [0x8D5F551B]");
        }
    };
};
