/* This autogenerated file is part of jpcsp. */
/*
This file is part of jpcsp.

Jpcsp is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

Jpcsp is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with Jpcsp.  If not, see <http://www.gnu.org/licenses/>.
 */

package jpcsp.HLE.modules150;

import jpcsp.HLE.modules.HLEModule;
import jpcsp.HLE.modules.HLEModuleFunction;
import jpcsp.HLE.modules.HLEModuleManager;

import jpcsp.Memory;
import jpcsp.Processor;

import jpcsp.Allegrex.CpuState; // New-Style Processor

public class sceUtility_netparam_internal implements HLEModule {
	@Override
	public String getName() { return "sceUtility_netparam_internal"; }
	
	@Override
	public void installModule(HLEModuleManager mm, int version) {
		if (version >= 150) {
		
			mm.addFunction(sceUtilityCreateNetParamFunction, 0x072DEBF2);
			mm.addFunction(sceUtilityDeleteNetParamFunction, 0x9CE50172);
			mm.addFunction(sceUtilityCopyNetParamFunction, 0xFB0C4840);
			mm.addFunction(sceUtilitySetNetParamFunction, 0xFC4516F3);
			
		}
	}
	
	@Override
	public void uninstallModule(HLEModuleManager mm, int version) {
		if (version >= 150) {
		
			mm.removeFunction(sceUtilityCreateNetParamFunction);
			mm.removeFunction(sceUtilityDeleteNetParamFunction);
			mm.removeFunction(sceUtilityCopyNetParamFunction);
			mm.removeFunction(sceUtilitySetNetParamFunction);
			
		}
	}
	
	
	public void sceUtilityCreateNetParam(Processor processor) {
		// CpuState cpu = processor.cpu; // New-Style Processor
		Processor cpu = processor; // Old-Style Processor
		Memory mem = Processor.memory;
		
		/* put your own code here instead */

		// int a0 = cpu.gpr[4];  int a1 = cpu.gpr[5];  ...  int t3 = cpu.gpr[11];
		// float f12 = cpu.fpr[12];  float f13 = cpu.fpr[13];  ... float f19 = cpu.fpr[19];

		System.out.println("Unimplemented NID function sceUtilityCreateNetParam [0x072DEBF2]");

		cpu.gpr[2] = 0xDEADC0DE;

		// cpu.gpr[2] = (int)(result & 0xffffffff);  cpu.gpr[3] = (int)(result  32); cpu.fpr[0] = result;
	}
    
	public void sceUtilityDeleteNetParam(Processor processor) {
		// CpuState cpu = processor.cpu; // New-Style Processor
		Processor cpu = processor; // Old-Style Processor
		Memory mem = Processor.memory;
		
		/* put your own code here instead */

		// int a0 = cpu.gpr[4];  int a1 = cpu.gpr[5];  ...  int t3 = cpu.gpr[11];
		// float f12 = cpu.fpr[12];  float f13 = cpu.fpr[13];  ... float f19 = cpu.fpr[19];

		System.out.println("Unimplemented NID function sceUtilityDeleteNetParam [0x9CE50172]");

		cpu.gpr[2] = 0xDEADC0DE;

		// cpu.gpr[2] = (int)(result & 0xffffffff);  cpu.gpr[3] = (int)(result  32); cpu.fpr[0] = result;
	}
    
	public void sceUtilityCopyNetParam(Processor processor) {
		// CpuState cpu = processor.cpu; // New-Style Processor
		Processor cpu = processor; // Old-Style Processor
		Memory mem = Processor.memory;
		
		/* put your own code here instead */

		// int a0 = cpu.gpr[4];  int a1 = cpu.gpr[5];  ...  int t3 = cpu.gpr[11];
		// float f12 = cpu.fpr[12];  float f13 = cpu.fpr[13];  ... float f19 = cpu.fpr[19];

		System.out.println("Unimplemented NID function sceUtilityCopyNetParam [0xFB0C4840]");

		cpu.gpr[2] = 0xDEADC0DE;

		// cpu.gpr[2] = (int)(result & 0xffffffff);  cpu.gpr[3] = (int)(result  32); cpu.fpr[0] = result;
	}
    
	public void sceUtilitySetNetParam(Processor processor) {
		// CpuState cpu = processor.cpu; // New-Style Processor
		Processor cpu = processor; // Old-Style Processor
		Memory mem = Processor.memory;
		
		/* put your own code here instead */

		// int a0 = cpu.gpr[4];  int a1 = cpu.gpr[5];  ...  int t3 = cpu.gpr[11];
		// float f12 = cpu.fpr[12];  float f13 = cpu.fpr[13];  ... float f19 = cpu.fpr[19];

		System.out.println("Unimplemented NID function sceUtilitySetNetParam [0xFC4516F3]");

		cpu.gpr[2] = 0xDEADC0DE;

		// cpu.gpr[2] = (int)(result & 0xffffffff);  cpu.gpr[3] = (int)(result  32); cpu.fpr[0] = result;
	}
    
	public final HLEModuleFunction sceUtilityCreateNetParamFunction = new HLEModuleFunction("sceUtility_netparam_internal", "sceUtilityCreateNetParam") {
		@Override
		public final void execute(Processor processor) {
			sceUtilityCreateNetParam(processor);
		}
		@Override
		public final String compiledString() {
			return "jpcsp.HLE.Modules.sceUtility_netparam_internalModule.sceUtilityCreateNetParam(processor);";
		}
	};
    
	public final HLEModuleFunction sceUtilityDeleteNetParamFunction = new HLEModuleFunction("sceUtility_netparam_internal", "sceUtilityDeleteNetParam") {
		@Override
		public final void execute(Processor processor) {
			sceUtilityDeleteNetParam(processor);
		}
		@Override
		public final String compiledString() {
			return "jpcsp.HLE.Modules.sceUtility_netparam_internalModule.sceUtilityDeleteNetParam(processor);";
		}
	};
    
	public final HLEModuleFunction sceUtilityCopyNetParamFunction = new HLEModuleFunction("sceUtility_netparam_internal", "sceUtilityCopyNetParam") {
		@Override
		public final void execute(Processor processor) {
			sceUtilityCopyNetParam(processor);
		}
		@Override
		public final String compiledString() {
			return "jpcsp.HLE.Modules.sceUtility_netparam_internalModule.sceUtilityCopyNetParam(processor);";
		}
	};
    
	public final HLEModuleFunction sceUtilitySetNetParamFunction = new HLEModuleFunction("sceUtility_netparam_internal", "sceUtilitySetNetParam") {
		@Override
		public final void execute(Processor processor) {
			sceUtilitySetNetParam(processor);
		}
		@Override
		public final String compiledString() {
			return "jpcsp.HLE.Modules.sceUtility_netparam_internalModule.sceUtilitySetNetParam(processor);";
		}
	};
    
};
